### Research on 20 in built method on pandas and 20 on numpy with examples each.

### Numpy::

### 1. append() : The .append() function adds values to the end of an array and returns a ndarray with the values appended.



In [2]:
import numpy as np

In [9]:
a1 = np.arange(1,10)
a2 = np.arange(1,6,2)

print(a1)
print(a2)
print(np.append(a1,a2))

[1 2 3 4 5 6 7 8 9]
[1 3 5]
[1 2 3 4 5 6 7 8 9 1 3 5]


### 2. log() : The .log() function returns an element-wise natural logarithm of an array

In [10]:
print(np.log(a1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### 3. sum() : The .sum() function sums the elements of an array over a given axis.

In [15]:
nd = np.array([[1,2,3],[4,5,6]])

print(np.sum(nd))
print(np.sum(nd, axis=0))
print(np.sum(nd, axis=1))

21
[5 7 9]
[ 6 15]


In [14]:
print(np.sum(a1))

45


### 4. Transpose() : The .transpose() function reverses or permutes the axes of an ndarray

In [16]:
num = np.array([[1,2,3],[4,5,6]])

print(num)
print(np.transpose(num))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 5. linspace : The .linspace() function returns an array of evenly-spaced numbers over a specified interval [start,stop], optionally excluding the stop value.

In [20]:
result = np.linspace(10, 20, num=6)
print(result)

result2 = np.linspace(10, 20, num=6, endpoint=False)
print(result2)



[10. 12. 14. 16. 18. 20.]
[10.         11.66666667 13.33333333 15.         16.66666667 18.33333333]


### 6. reshape() : The .reshape() function rearranges the data in an ndarray into a new shape. The new shape must be compatible with the old one, though an index of -1 can be used to infer one dimension.



In [21]:

print(np.reshape(a1,(3,3)))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 7. repeat() : The numpy.repeat(a, repeats, axis=None) function repeats the elements of an array. The number of repetitions is specified by the second argument repeats.

In [26]:
# repeat string '2015' 5 times
np.repeat("2015",5)

array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

In [24]:
# repeat number 3 5 times
np.repeat(3,5)


array([3, 3, 3, 3, 3])

### 8. random

### random.randint : The numpy.random.randint(low, high=None, size=None, dtype=’l’) function returns random integers from the interval [low,high). If high parameter is missing (None), the random numbers are selected from the interval [0,low). By default, a single random number(int) is returned. To generate a narray of random integers, the shape of the array is provided in the parameter size.

In [28]:
# toss a coin
np.random.randint(2)




0

In [29]:
# toss a coin 5 times
np.random.randint(2,size=5)



array([0, 1, 0, 0, 0])

In [30]:
# roll a dice
np.random.randint(1,7)


1

In [31]:
# roll a dice 10 times
np.random.randint(1,7,size=10)


array([6, 4, 2, 4, 6, 3, 1, 2, 4, 1])

### 9. random.choice : The numpy.random.choice(a, size=None, replace=True, p=None) returns a random sample from a given array. By default, a single value is returned. To return more elements, the output shape can be specified in the parameter size as we did before with the numpy.random.randint function.

In [32]:
# toss a coin
np.random.choice([0,1])





0

In [33]:
# toss a coin 5 times
np.random.choice([0,1],size=5)




array([1, 0, 1, 0, 1])

In [34]:
# roll a dice
np.random.choice([1,2,3,4,5,6])



4

In [35]:
np.random.choice([1,2,3,4,5,6],size=10)
#array([3, 5, 6, 6, 6, 2, 5, 5, 1, 2])

array([1, 6, 1, 3, 5, 4, 4, 1, 6, 3])

### 10. random.binomial : The numpy.random.binomial(n, p, size=None) draws samples from a binomial distribution. The binomial distribution is used when there are two mutually exclusive outcomes, providing the number of successes of n trials with a probability of success on a single trial p.

In [36]:
# number of successes (number of heads) in 10 coin flips
np.random.binomial(10,0.5)




8

In [37]:
# number of successes (number of heads) in 10 coin flips - biased coin with a 0.8 probability of obtaining heads
np.random.binomial(10,0.8)


8

### 11. argmax : The numpy.argmax(a, axis=None, out=None) function returns the indices of the maximum values along an axis.

In [38]:
# numpy array
array = np.array([[1,2,3],[4,5,6]])

# index of maximum value
max_value = np.argmax(array)

max_value

5

### 12 .squeeze(): The numpy.squeeze(a, axis=None) removes single-dimensional entries from the shape of an array. The argument axis specifies the axis we want to squeeze out. If the shape of the selected axis is greater than 1 a ValueError is raised.

In [40]:
print(a1)
np.shape(a1)
np.squeeze(a1)

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:

# numpy array of shape (1,2,1)

arr = np.array([[[1],[1]]])

arr.shape

# squeeze out axis 0
arr0 = np.squeeze(arr,axis=0)
arr0
#array([[1],[1]])
arr0.shape



(2, 1)

### 13. split() ; The split function helps splitting an array into multiple sub-arrays of equal or near-equal size.


In [45]:

a = np.arange(8)
print (a)
print ("sub-parts of array a:", np.split(a, 4))

[0 1 2 3 4 5 6 7]
sub-parts of array a: [array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]


### 14: square() : This mathematical function helps user to calculate square value of each element in the array.

In [61]:
ar1 = [1, -3, 15, -466]
print ("Square Value of ar1 : \n", np.square(ar1))
  
ar2 = [23 ,-56]
print ("\nSquare Value of ar2 : ", np.square(ar2))

Square Value of ar1 : 
 [     1      9    225 217156]

Square Value of ar2 :  [ 529 3136]


### 15. sort() : Sorting means putting elements in an ordered sequence.

### Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.



In [54]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


### 16. where() : You can search an array for a certain value, and return the indexes that get a match.

### To search an array, use the where() method.

In [55]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
# Which means that the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6], dtype=int64),)


### 17. min() : It returns the minimum value from the passed numpy array

In [56]:
arr.min()

1

### 18. max() : It returns the maximum value from the passed numpy array

In [57]:
arr.max()

5

### 19. reciprocal(): This mathematical function is used to calculate reciprocal of all the elements in the input array

In [58]:
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


### divide() ; Array element from first array is divided by elements from second element (all happens element-wise). Both arr1 and arr2 must have same shape and element in arr2 must not be zero; otherwise it will raise an error. 

In [59]:
# input_array
arr1 = [2, 27, 2, 21, 23]
arr2 = [2, 3, 4, 5, 6]
print ("arr1         : ", arr1)
print ("arr2         : ", arr2)
 
# output_array
out = np.divide(arr1, arr2)
print ("\nOutput array : \n", out)

arr1         :  [2, 27, 2, 21, 23]
arr2         :  [2, 3, 4, 5, 6]

Output array : 
 [1.         9.         0.5        4.2        3.83333333]
