20 inbuilt methods in Numpy

In [16]:
#array method. returns output as an array
import numpy as np
x = [1, 8, 2, 3, 5]
nums = np.array([1, 8, 2, 3, 5])
type(nums)

numpy.ndarray

In [17]:
#arithmetic operation with arrays
nums3 = nums + nums
nums3

array([ 2, 16,  4,  6, 10])

In [18]:
#log function
nums3 = np.log(nums)
print(nums3)

[0.         2.07944154 0.69314718 1.09861229 1.60943791]


In [19]:
#exponential function
nums3 = np.exp(nums)
print(nums3)

[2.71828183e+00 2.98095799e+03 7.38905610e+00 2.00855369e+01
 1.48413159e+02]


In [ ]:
#arange method. takes the start and end index plus an optional step size.
nums = np.arange(3,9,2)
nums

array([3, 5, 7])

In [42]:
#indexing with one dimensional arrays
nums = np.arange(3,9)
print(nums[3])

6


In [43]:
#print numbers in a range by indexing
print(nums[1:6])

[4 5 6 7 8]


In [44]:
#slicing. start index, stop index, step size
nums[1:7:2]

array([4, 6, 8])

In [32]:
#reshape method. to convert 1d array into 2d array
nums = np.arange(1,13)
nums
nums2=nums.reshape(4,3)
nums2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#zeros method. creates an array of only zeroes
zeroes = np.zeros(8)
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#2 dimensional array of zeroes
zeroes = np.zeros([3,5])
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#ones method. creates an array of only ones
ones = np.ones(4)
ones

array([1., 1., 1., 1.])

In [ ]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [ ]:
#linspace method takes start and end indexes and number of linearly spaced numbers needed in a specified range
linspace = np.linspace(1,5,10)
linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#eye method. used to make identity matrix
idn = np.eye(3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#random method. to create arrays with random numbers.
random = np.random.rand(2,4)
random

array([[0.09319346, 0.83142385, 0.51205973, 0.72307443],
       [0.09501085, 0.45092956, 0.7861287 , 0.49893605]])

In [ ]:
#random method to return matrix of normal distribution
random = np.random.randn(2,4)
random

array([[-0.33103789, -1.02503366,  0.21933478, -0.89119722],
       [ 2.06676377, -0.87315649, -1.0346524 ,  0.49690136]])

In [ ]:
#random method to create array for random integers.
# upper and lower limits, and how many integers to 
# return are defined
random = np.random.randint(10,20,4)
random

array([11, 14, 12, 19])

In [35]:
#min method
random = np.random.randint(1,50,10)
random

array([ 2, 23, 21, 36, 21, 49,  2, 43, 38, 25])

In [36]:
xmin = random.min()
xmin

2

In [37]:
xmax = random.max()
xmax

49

In [38]:
#arg method to return the index of the minimum and maximum values
print(random.argmax())

5


In [39]:
print(random.argmin())

0


20 inbuilt pandas methods

In [21]:
import numpy as np
import pandas as pd

In [26]:
#labels method
labels = ["x","y","z"]
list = [13, 69, 42]
arr = np.array([13, 69, 42])
w = {"x":13, "y":69, "z":42}
print(w)

{'x': 13, 'y': 69, 'z': 42}


In [29]:
# Creating a series
pd.Series(data = list)


0    13
1    69
2    42
dtype: int64

In [30]:
#creating a dataframe
chimeras = pd.DataFrame({"Name":["Elish", "Sanguine", "Drake", "Jade"], "Age": [95,75,72,19], "Salary": [100000, 20000, 40000, 10000],})
chimeras

Name  Age  Salary
0     Elish   95  100000
1  Sanguine   75   20000
2     Drake   72   40000
3      Jade   19   10000

In [33]:
#find the largest value in dataframe
chimeras["Salary"].max()

100000

In [34]:
#find smallest value in dataframe
chimeras["Age"].max()

95

In [35]:
#describe. generating desriptvie statistics
chimeras.describe()

Age         Salary
count   4.000000       4.000000
mean   65.250000   42500.000000
std    32.479481   40311.288741
min    19.000000   10000.000000
25%    58.750000   17500.000000
50%    73.500000   30000.000000
75%    80.000000   55000.000000
max    95.000000  100000.000000

In [36]:
#dtypes
chimeras.dtypes

Name      object
Age        int64
Salary     int64
dtype: object

In [37]:
#head method. returns required number of rows
chimeras.head(2)

Name  Age  Salary
0     Elish   95  100000
1  Sanguine   75   20000

In [38]:
#print summary of data frama
chimeras.info

<bound method DataFrame.info of        Name  Age  Salary
0     Elish   95  100000
1  Sanguine   75   20000
2     Drake   72   40000
3      Jade   19   10000>

In [39]:
#calculate mean of values in data frame
chimeras["Age"].mean()

65.25

In [40]:
#median value in data frame
chimeras["Salary"].median()

30000.0

In [42]:
#changing a string to lower case or uppercase
chimeras["Name"].str.upper()

0       ELISH
1    SANGUINE
2       DRAKE
3        JADE
Name: Name, dtype: object

In [43]:
#capitalize first letter of items in string
chimeras["Name"].str.capitalize()

0       Elish
1    Sanguine
2       Drake
3        Jade
Name: Name, dtype: object

In [44]:
# looks up a value and returns true or false if the value is there or not
chimeras["Name"].str.contains("Silas")

0    False
1    False
2    False
3    False
Name: Name, dtype: bool

In [46]:
#look up value and return true for where the value is and false for where it is not
chimeras["Name"].str.contains("Elish")

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [47]:
#finds the number of characters in a string
chimeras["Name"].str.len()

0    5
1    8
2    5
3    4
Name: Name, dtype: int64

In [48]:
#returns the index with the longest characters
chimeras["Name"].str.len().idxmax()

1

In [50]:
#using index
brothers = pd.Series([1,2,3,4,5], index = ["Joaquin", "Apollo", "Artemis", "Ares", "Reaver"])
brothers


Joaquin    1
Apollo     2
Artemis    3
Ares       4
Reaver     5
dtype: int64

In [53]:
# adding two series
gen1_IQ = pd.Series([95,93,65], index = ["Elish", "Ellis", "Nero"])
gen1_IQ1 = pd.Series([105,120,72], index = ["Elish", "Ellis", "Nero"] )
gen1_IQ + gen1_IQ1

Elish    200
Ellis    213
Nero     137
dtype: int64

In [54]:
from numpy.random import randn
np.random.seed(50)

In [56]:
#arranges data into rows and columns
df = pd.DataFrame(randn(5,4), index = 'F G H J K '.split(), columns = 'S P Q R'.split())
df

S         P         Q         R
F  0.139531  0.285469 -0.281262  1.710907
G -0.149767  0.690307  1.095210  1.338409
H -1.368982  0.486428  0.753522  0.363465
J -0.314710  1.373281 -0.624417  0.375754
K -0.200416  0.743038  0.857362 -1.506189

In [57]:
#removing a column from a data frame
new = df.drop("R", axis = 1)
new

S         P         Q
F  0.139531  0.285469 -0.281262
G -0.149767  0.690307  1.095210
H -1.368982  0.486428  0.753522
J -0.314710  1.373281 -0.624417
K -0.200416  0.743038  0.857362

In [58]:
# loc method. indexes and returns its elements
new.loc["H"]

S   -1.368982
P    0.486428
Q    0.753522
Name: H, dtype: float64

In [63]:
#iloc method. uses index to look up values
new.iloc[1]

S   -0.149767
P    0.690307
Q    1.095210
Name: G, dtype: float64