## Ajoke Yusuf

### Numpy Function

In [1]:
import numpy as np

1. **eye()**

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2. **arange()**

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

3. **zeros()**

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

4. **ones()**

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

5. **linspace()**

In [6]:
np.linspace(0,15,10)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

6. **random.rand()**

In [7]:
np.random.rand(4)

array([0.63338303, 0.39456475, 0.21167285, 0.24615442])

7. **random.randint()**

In [8]:
np.random.randint(95,100)

99

8. **random.randn()**

In [9]:
np.random.randn(5,7)

array([[-0.70585372, -0.39636939, -0.28963836, -1.75417647,  0.10530366,
         1.44464767,  1.89776012],
       [ 1.78918001,  1.11448461,  0.3231061 , -0.15516951,  0.73527332,
         0.08832143,  1.34148858],
       [-0.30675931,  1.79358545,  1.10007472,  1.78021234,  0.46455359,
         1.61155831,  1.34867607],
       [-0.86902849,  1.74069583, -0.71431349,  0.64825353, -0.23383409,
        -0.07059382,  0.52649747],
       [ 0.06741067,  0.58625624,  0.55740599,  0.70826982, -0.14285265,
        -0.30296301, -1.45921837]])

9. **transpose()**

In [10]:
arr = ([1,4,78,12],
        [2,5,15,29],
        [3,6,7,18])
np.transpose(arr)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [78, 15,  7],
       [12, 29, 18]])

10. **sum()**

In [11]:
np.sum(arr)

180

11. **std()**

In [12]:
np.std(arr)

20.530465167647808

12. **min()**

In [13]:
np.min(arr)

1

13. **max()**

In [14]:
np.max(arr)

78

14. **argmax()**

In [15]:
np.argmax(arr)

2

15. **argmin()**

In [16]:
np.argmin(arr)

0

16. **reshape()**

In [17]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Pandas Function

In [18]:
import pandas as pd

In [19]:
df =pd.DataFrame({"Name": ['Ajoke','Chidinma', 'Femi', 'Tomi','Seun'],
      "Age": [24, 65, 35,np.nan, 56],
      "Country": ['Nigeria','China',np.nan,'Canada', 'China'],
       "Animal": ['Dog','Cat','Lion', 'Kangaroo','Goat']})

1. **info()**

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Name     5 non-null      object 
 1   Age      4 non-null      float64
 2   Country  4 non-null      object 
 3   Animal   5 non-null      object 
dtypes: float64(1), object(3)
memory usage: 288.0+ bytes


2. **head()**

In [21]:
df.head(2)

Name   Age  Country Animal
0     Ajoke  24.0  Nigeria    Dog
1  Chidinma  65.0    China    Cat

3. **tail()**

In [22]:
df.tail(2)

Name   Age Country    Animal
3  Tomi   NaN  Canada  Kangaroo
4  Seun  56.0   China      Goat

4. **isna()**

In [23]:
df.isna().sum()

Name       0
Age        1
Country    1
Animal     0
dtype: int64

5. **set_axis()**

In [24]:
df.set_axis(['a', 'b', 'c', 'd','e'], axis=0)

Name   Age  Country    Animal
a     Ajoke  24.0  Nigeria       Dog
b  Chidinma  65.0    China       Cat
c      Femi  35.0      NaN      Lion
d      Tomi   NaN   Canada  Kangaroo
e      Seun  56.0    China      Goat

6. **drop()**

In [25]:
df.drop(['Age'], axis=1)

Name  Country    Animal
0     Ajoke  Nigeria       Dog
1  Chidinma    China       Cat
2      Femi      NaN      Lion
3      Tomi   Canada  Kangaroo
4      Seun    China      Goat

7. **dropna()**

In [26]:
df.dropna()

Name   Age  Country Animal
0     Ajoke  24.0  Nigeria    Dog
1  Chidinma  65.0    China    Cat
4      Seun  56.0    China   Goat

8. **sort_values()**

In [27]:
df.sort_values(by='Country')

Name   Age  Country    Animal
3      Tomi   NaN   Canada  Kangaroo
1  Chidinma  65.0    China       Cat
4      Seun  56.0    China      Goat
0     Ajoke  24.0  Nigeria       Dog
2      Femi  35.0      NaN      Lion

9. **drop_duplicates()**

In [28]:
df.drop_duplicates()

Name   Age  Country    Animal
0     Ajoke  24.0  Nigeria       Dog
1  Chidinma  65.0    China       Cat
2      Femi  35.0      NaN      Lion
3      Tomi   NaN   Canada  Kangaroo
4      Seun  56.0    China      Goat

10. **describe()**

In [29]:
df.describe()

Age
count   4.000000
mean   45.000000
std    18.814888
min    24.000000
25%    32.250000
50%    45.500000
75%    58.250000
max    65.000000

11. **value_counts()**

In [30]:
df['Country'].value_counts()

China      2
Nigeria    1
Canada     1
Name: Country, dtype: int64

12. **replace()**

In [31]:
df.replace(np.nan, 0)

Name   Age  Country    Animal
0     Ajoke  24.0  Nigeria       Dog
1  Chidinma  65.0    China       Cat
2      Femi  35.0        0      Lion
3      Tomi   0.0   Canada  Kangaroo
4      Seun  56.0    China      Goat

13. **rename()**

In [32]:
df.rename({'Name':'First_Name'},axis=1)

First_Name   Age  Country    Animal
0      Ajoke  24.0  Nigeria       Dog
1   Chidinma  65.0    China       Cat
2       Femi  35.0      NaN      Lion
3       Tomi   NaN   Canada  Kangaroo
4       Seun  56.0    China      Goat

14. **count()**

In [33]:
df['Country'].count()

4

15. **pivot_table()**

In [34]:
df.pivot_table(index='Name', columns='Country', values='Age')

Country   China  Nigeria
Name                    
Ajoke       NaN     24.0
Chidinma   65.0      NaN
Seun       56.0      NaN

16. **shape**

In [35]:
df.shape

(5, 4)

17. **dtypes**

In [36]:
df.dtypes

Name        object
Age        float64
Country     object
Animal      object
dtype: object

18. **unique()**

In [37]:
df['Country'].unique()

array(['Nigeria', 'China', nan, 'Canada'], dtype=object)

19. **nunique()**

In [38]:
df.nunique()

Name       5
Age        4
Country    3
Animal     5
dtype: int64

20. **groupby()**

In [39]:
df.groupby('Name')['Country'].value_counts()

Name      Country
Ajoke     Nigeria    1
Chidinma  China      1
Seun      China      1
Tomi      Canada     1
Name: Country, dtype: int64