In [89]:
import numpy as np

### 1. Creating an array

In [90]:
a = np.array ([1,2,3,4])
print(a)

[1 2 3 4]


In [91]:
b = np.array([[3,4,5,],[6,7,8]])
print(b)

[[3 4 5]
 [6 7 8]]


### 2. Getting the dimensions of the array

In [92]:
a.ndim

1

In [93]:
b.ndim

2

### 3. Get shape

In [94]:
a.shape

(4,)

In [95]:
b.shape

(2, 3)

### 4. Getting type


In [97]:
a.dtype

dtype('int32')

In [98]:
b.dtype

dtype('int32')

### 5.Get size


In [99]:
a.itemsize

4

### 6. Get total size


In [119]:
a.size*a.itemsize 

16

In [120]:
b.size*b.itemsize

24

In [121]:
# OR
a.nbytes

16

In [122]:

b.nbytes

24

### 7. arrange: Return evenly spaced values within a given interval.

In [154]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### 8. All 1s matrix


In [126]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 9.  Random Decimal number


In [127]:
np.random.rand(4,2)

array([[0.79844965, 0.46638252],
       [0.10030767, 0.7624191 ],
       [0.89164678, 0.23442672],
       [0.46971368, 0.52419522]])

### 10. Random integer values


In [128]:
np.random.randint(-3,5, size=(2,2))

array([[ 3, -3],
       [-3,  1]])

### 11.  The identity matrix


In [129]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 12. Repeating array


In [130]:
arr = np.array([[1,2,4]])
A1 = np.repeat(arr,3, axis = 0)
print(A1)

[[1 2 4]
 [1 2 4]
 [1 2 4]]


### 13. Copying arrays


In [131]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

### 14. Getting the maximum value

In [132]:
n = a.max()
print("Largest value")
print(n)

Largest value
3


### 15. Getting the minimum value

In [139]:
n = a.min()
print("smallest value")
print(n)

smallest value
1


### 16. Appending arrays

In [140]:
print("Original array")
numbers = np.arange(8)
print(numbers)
print("\n")
print("Array with appended values at the end")
print(np.append(numbers, (8,9,10)))

Original array
[0 1 2 3 4 5 6 7]


Array with appended values at the end
[ 0  1  2  3  4  5  6  7  8  9 10]


In [141]:
print("Original array")
q = np.arange(2,11).reshape (3,3)
print(q)
print("\n")
print("Arrays with appended values at the end")
print(np.append(q, [[12,13,14]], axis = 0))

Original array
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Arrays with appended values at the end
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


### 17. Printing all boarders 1s and 0s inside

In [142]:
print("Original array")
array_2d = np.ones((6,6))
print(array_2d)
print("\n")
print("Arrays with one on the boarder and zeros inside")
array_2d[1:-1,1:-1] = 0
print(array_2d)

Original array
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


Arrays with one on the boarder and zeros inside
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 18. eye: Another way of printing identity matrix

In [143]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 19. linspace: Return evenly spaced numbers over a specified interval.

In [144]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

### 20. printing all zeros arrays

In [151]:
np.zeros((3))

array([0., 0., 0.])

# 20 FUNCTIONS IN PANDAS

In [15]:
import pandas as pd

### 1. Creating a table from the scratch  using dictionary

In [18]:
Table = {"Names": ["Chisom", "Ugomsi", "Nneka", "Oge", "Blessing"],
        "Age":[25, 1, 23, 24, 22],
        "States": ["Enugu", "Enugu", "Anambra", "Ebonyi", "Abia"]}

In [19]:
df = pd.DataFrame(Table)

In [20]:
df

Names  Age   States
0    Chisom   25    Enugu
1    Ugomsi    1    Enugu
2     Nneka   23  Anambra
3       Oge   24   Ebonyi
4  Blessing   22     Abia

### 2. Sum: Return the sum of the values over the requested axis.


In [24]:
df["Age"].sum ()

95

In [28]:
df["Age"][0:2].sum()

26

### 3. Mean: Return the mean of the values over the requested axis.

In [34]:
df["Age"].mean()

19.0

### 4. Min: Return the minimum of the values over the requested axis.


In [36]:
df["Age"].min()

1

### 5. Max: Return the maximum of the values over the requested axis.

In [37]:
df["Age"].max()

25

### 6. Count: Count non-NA cells for each column or row.

In [42]:
df["Age"].count()

5

### 7. df.columns: Used to find the columns on the table

In [50]:
df.columns

Index(['Names', 'Age', 'States'], dtype='object')

### 8. Loc: Access a group of rows and columns by label(s) or a boolean array.


In [55]:
df.loc[0]

Names     Chisom
Age           25
States     Enugu
Name: 0, dtype: object

In [67]:
df.loc[0:2, "Names"]

0    Chisom
1    Ugomsi
2     Nneka
Name: Names, dtype: object

### 9. iloc: Purely integer-location based indexing for selection by position.


In [69]:
df.iloc~[0:2]

Names  Age States
0  Chisom   25  Enugu
1  Ugomsi    1  Enugu

### 10. Where: Replace values where the condition is False.


In [61]:
# method chaining (Equivalance of sumif)
df["Age"].where(df["Age"]>20).sum()

94.0

### 11. Value_counts: Return a Series containing counts of unique rows in the DataFrame.


In [63]:
# method chain (Equivalance of countif)
df["Age"].where(df["Age"]>20).value_counts()

25.0    1
23.0    1
24.0    1
22.0    1
Name: Age, dtype: int64

In [64]:
df["Age"].where(df["Age"]>20).value_counts().sum()

4

### 12. Count: Count non-NA cells for each column or row.

In [66]:
df["Age"].where(df["Age"]>20).count()

4

### 13. pd.read: Read an Excel file into a pandas DataFrame.

In [101]:
df = pd.read_excel("Order sales pandas.xlsx")

### 14. head: This function returns the first `n` rows for the object based on position. It is useful for quickly testing if your object
### has the right type of data in it.

In [108]:
df.head()

Order Quantity       Sales  Discount       Ship Mode     Profit  \
0               6    261.5400      0.04     Regular Air  -213.2500   
1              49  10123.0200      0.07  Delivery Truck   457.8100   
2              27    244.5700      0.01     Regular Air    46.7075   
3              30   4965.7595      0.08     Regular Air  1198.9710   
4              19    394.2700      0.08     Regular Air    30.9400   

   Unit Price  Shipping Cost       Customer Name Province   Region  \
0       38.94          35.00  Muhammed MacIntyre  Nunavut  Nunavut   
1      208.16          68.02        Barry French  Nunavut  Nunavut   
2        8.69           2.99        Barry French  Nunavut  Nunavut   
3      195.99           3.99       Clay Rozendal  Nunavut  Nunavut   
4       21.78           5.94      Carlos Soltero  Nunavut  Nunavut   

  Customer Segment Product Category            Product Sub-Category  \
0   Small Business  Office Supplies          Storage & Organization   
1         Consumer  Office Supplies                      Appliances   
2         Consumer  Office Supplies  Binders and Binder Accessories   
3        Corporate       Technology    Telephones and Communication   
4         Consumer  Office Supplies                      Appliances   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum   
2   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl         Small Box   
3                                               R380         Small Box   
4                           Holmes HEPA Air Purifier        Medium Box   

   Product Base Margin  Ship Date  
0                 0.80 2010-10-20  
1                 0.58 2012-10-02  
2                 0.39 2012-10-03  
3                 0.58 2011-07-12  
4                 0.50 2010-08-30

### 15. info: Print a concise summary of a DataFrame.

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Order Quantity        8399 non-null   int64         
 1   Sales                 8399 non-null   float64       
 2   Discount              8399 non-null   float64       
 3   Ship Mode             8399 non-null   object        
 4   Profit                8399 non-null   float64       
 5   Unit Price            8399 non-null   float64       
 6   Shipping Cost         8399 non-null   float64       
 7   Customer Name         8399 non-null   object        
 8   Province              8399 non-null   object        
 9   Region                8399 non-null   object        
 10  Customer Segment      8399 non-null   object        
 11  Product Category      8399 non-null   object        
 12  Product Sub-Category  8399 non-null   object        
 13  Product Name      

### 16. Shape: Return a tuple representing the dimensionality of the DataFrame.

In [114]:
df.shape

(8399, 17)

### 17. Size: Return an int representing the number of elements in this object.

In [115]:
df.size

142783

### 18. Sample: Return a random sample of items from an axis of object.

In [116]:
df.sample(n=10)

Order Quantity      Sales  Discount       Ship Mode    Profit  \
5706               7   189.7300      0.01     Regular Air   43.1715   
1772              13   728.0250      0.04     Regular Air   19.9980   
2411              50   196.3900      0.07     Regular Air   82.6000   
7964              36  1921.1275      0.08     Regular Air  248.5800   
4329              47  1291.3500      0.04     Regular Air  479.6200   
3099              30   257.4200      0.01     Regular Air   59.1800   
2199               7    81.5800      0.04     Regular Air   -7.7800   
2143              28  1642.0500      0.03     Regular Air  829.7300   
1059              17  2285.1200      0.08  Delivery Truck -455.8000   
6147              19  6991.6500      0.08  Delivery Truck  906.8000   

      Unit Price  Shipping Cost     Customer Name          Province   Region  \
5706       24.95           2.99  Jennifer Jackson       Saskachewan   Prarie   
1772       65.99           2.50      Duane Benoit           Ontario  Ontario   
2411        4.13           0.50   George Ashbrook           Ontario  Ontario   
7964       65.99           8.99       Claire Good           Alberta     West   
4329       26.38           5.86     Odella Nelson           Ontario  Ontario   
3099        8.01           2.87     Sanjit Jacobs            Quebec   Quebec   
2199       10.98           3.37     Edward Nazzal           Ontario  Ontario   
2143       55.98           4.86    Linda Cazamias           Ontario  Ontario   
1059      140.98          36.09      Khloe Miller  British Columbia     West   
6147      399.98          12.06      Andy Gerbode       Saskachewan   Prarie   

     Customer Segment Product Category            Product Sub-Category  \
5706      Home Office  Office Supplies  Binders and Binder Accessories   
1772      Home Office       Technology    Telephones and Communication   
2411         Consumer  Office Supplies                          Labels   
7964      Home Office       Technology    Telephones and Communication   
4329   Small Business  Office Supplies                           Paper   
3099         Consumer  Office Supplies                           Paper   
2199      Home Office  Office Supplies   Scissors, Rulers and Trimmers   
2143        Corporate  Office Supplies                           Paper   
1059      Home Office        Furniture                       Bookcases   
6147         Consumer       Technology                 Office Machines   

                                           Product Name Product Container  \
5706                Large Capacity Hanging Post Binders         Small Box   
1772                                               6000         Small Box   
2411                                          Avery 506         Small Box   
7964                                    Talkabout T8367         Small Box   
4329                                         Xerox 1935         Small Box   
3099  TOPS Money Receipt Book, Consecutively Numbere...          Wrap Bag   
2199                         Fiskars® Softgrip Scissors        Small Pack   
2143                                         Xerox 1908         Small Box   
1059   Sauder Forest Hills Library, Woodland Oak Finish         Jumbo Box   
6147     Okidata ML320 Series Turbo Dot Matrix Printers         Jumbo Box   

      Product Base Margin  Ship Date  
5706                 0.39 2011-05-21  
1772                 0.55 2012-03-27  
2411                 0.39 2011-02-18  
7964                 0.56 2012-02-29  
4329                 0.39 2010-07-27  
3099                 0.40 2009-01-18  
2199                 0.57 2012-03-27  
2143                 0.36 2009-09-20  
1059                 0.77 2010-12-27  
6147                 0.56 2009-01-18

### 19. Describe: Generate descriptive statistics.Descriptive statistics include those that summarize the central
### tendency, dispersion and shape of a
### dataset's distribution, excluding ``NaN`` values.

In [117]:
df.describe()

Order Quantity         Sales     Discount        Profit   Unit Price  \
count     8399.000000   8399.000000  8399.000000   8399.000000  8399.000000   
mean        25.571735   1775.878179     0.049671    181.184422    89.346259   
std         14.481071   3585.050525     0.031823   1196.653326   290.354383   
min          1.000000      2.240000     0.000000 -14140.701600     0.990000   
25%         13.000000    143.195000     0.020000    -83.315000     6.480000   
50%         26.000000    449.420000     0.050000     -1.500000    20.990000   
75%         38.000000   1709.320000     0.080000    162.748000    85.990000   
max         50.000000  89061.050000     0.250000  27220.690000  6783.020000   

       Shipping Cost  Product Base Margin  
count    8399.000000          8336.000000  
mean       12.838557             0.512513  
std        17.264052             0.135589  
min         0.490000             0.350000  
25%         3.300000             0.380000  
50%         6.070000             0.520000  
75%        13.990000             0.590000  
max       164.730000             0.850000

In [155]:
# For Transposing
df.describe().T

count         mean          std         min      25%  \
Order Quantity       8399.0    25.571735    14.481071      1.0000   13.000   
Sales                8399.0  1775.878179  3585.050525      2.2400  143.195   
Discount             8399.0     0.049671     0.031823      0.0000    0.020   
Profit               8399.0   181.184422  1196.653326 -14140.7016  -83.315   
Unit Price           8399.0    89.346259   290.354383      0.9900    6.480   
Shipping Cost        8399.0    12.838557    17.264052      0.4900    3.300   
Product Base Margin  8336.0     0.512513     0.135589      0.3500    0.380   

                        50%       75%       max  
Order Quantity        26.00    38.000     50.00  
Sales                449.42  1709.320  89061.05  
Discount               0.05     0.080      0.25  
Profit                -1.50   162.748  27220.69  
Unit Price            20.99    85.990   6783.02  
Shipping Cost          6.07    13.990    164.73  
Product Base Margin    0.52     0.590      0.85

### 20. nunique: Count number of distinct elements in specified axis.

In [159]:
df.nunique()

Order Quantity            50
Sales                   8153
Discount                  16
Ship Mode                  3
Profit                  7986
Unit Price               751
Shipping Cost            652
Customer Name            795
Province                  13
Region                     8
Customer Segment           4
Product Category           3
Product Sub-Category      17
Product Name            1263
Product Container          7
Product Base Margin       51
Ship Date               1450
dtype: int64

### 21.df.isna().any():  Detect missing values.

In [161]:
df.isna().any()

Order Quantity          False
Sales                   False
Discount                False
Ship Mode               False
Profit                  False
Unit Price              False
Shipping Cost           False
Customer Name           False
Province                False
Region                  False
Customer Segment        False
Product Category        False
Product Sub-Category    False
Product Name            False
Product Container       False
Product Base Margin      True
Ship Date               False
dtype: bool

### 22. isnull: Detect missing values.

In [163]:
df.isnull()

Order Quantity  Sales  Discount  Ship Mode  Profit  Unit Price  \
0              False  False     False      False   False       False   
1              False  False     False      False   False       False   
2              False  False     False      False   False       False   
3              False  False     False      False   False       False   
4              False  False     False      False   False       False   
...              ...    ...       ...        ...     ...         ...   
8394           False  False     False      False   False       False   
8395           False  False     False      False   False       False   
8396           False  False     False      False   False       False   
8397           False  False     False      False   False       False   
8398           False  False     False      False   False       False   

      Shipping Cost  Customer Name  Province  Region  Customer Segment  \
0             False          False     False   False             False   
1             False          False     False   False             False   
2             False          False     False   False             False   
3             False          False     False   False             False   
4             False          False     False   False             False   
...             ...            ...       ...     ...               ...   
8394          False          False     False   False             False   
8395          False          False     False   False             False   
8396          False          False     False   False             False   
8397          False          False     False   False             False   
8398          False          False     False   False             False   

      Product Category  Product Sub-Category  Product Name  Product Container  \
0                False                 False         False              False   
1                False                 False         False              False   
2                False                 False         False              False   
3                False                 False         False              False   
4                False                 False         False              False   
...                ...                   ...           ...                ...   
8394             False                 False         False              False   
8395             False                 False         False              False   
8396             False                 False         False              False   
8397             False                 False         False              False   
8398             False                 False         False              False   

      Product Base Margin  Ship Date  
0                   False      False  
1                   False      False  
2                   False      False  
3                   False      False  
4                   False      False  
...                   ...        ...  
8394                False      False  
8395                False      False  
8396                False      False  
8397                False      False  
8398                False      False  

[8399 rows x 17 columns]

### 23. columns: Immutable sequence used for indexing and alignment. The basic object storing axis labels for all ### pandas objects.

In [164]:
df.columns

Index(['Order Quantity', 'Sales', 'Discount', 'Ship Mode', 'Profit',
       'Unit Price', 'Shipping Cost', 'Customer Name', 'Province', 'Region',
       'Customer Segment', 'Product Category', 'Product Sub-Category',
       'Product Name', 'Product Container', 'Product Base Margin',
       'Ship Date'],
      dtype='object')