20 Inbuilt method in Numpy

In [1]:
import numpy as np

# 1 Numpy array Method
np.array()

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

# 2 Numpy array of Zeros
np.zeros()


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# 3. Numpy array of ones
np.ones()

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# 4 Numpy array of eye
np.eye()

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 5 Numpy array of arange
np.arange()

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 6 Numpy array of linspace
np.linspace()

In [11]:
np.linspace(start = 10, stop = 20, num = 5)

array([10. , 12.5, 15. , 17.5, 20. ])

# 7 Numpy array of random
 np.random.random()

In [12]:
np.random.random(size = 10)

array([0.17789792, 0.98440782, 0.0353574 , 0.22920461, 0.37082226,
       0.71932024, 0.10466213, 0.41871602, 0.77380762, 0.13663959])

# 8 Numpy array of identity
 np.identity()

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 9 Numpy array of empty
np.empty()

In [14]:
np.empty([2, 2])

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.43329965e-311]])

# 10 Numpy array of empty_like
np.empty_like()


In [16]:
a = ([1,2,3], [4,5,6]) 
np.empty_like(a)

array([[         0, 1072693248,          0],
       [1072693248,          0, 1072693248]])

# 11 Numpy array of full
np.full()

In [17]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

# 12 Numpy array of asarray
np.asarray()

In [18]:
a = [1, 2]
np.asarray(a)

array([1, 2])

# 13 Numpy array of asanyarray
np.asanyarray()

In [19]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

# 14 Numpy array of asfarray
np.asfarray()

In [29]:
np.asfarray([2, 3])

array([2., 3.])

# 15 Numpy array of asmatrix
np.asmatrix()

In [35]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m


matrix([[5, 2],
        [3, 4]])

# 16 Numpy array of stack

In [33]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

# 17 Numpy array of block
np.block()

In [40]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

# 18 Numpy array of vstack
np.vstack()

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

# 19 Numpy array of hstack
np.hstack()

In [42]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# 20 Numpy array of split
np.split()

In [43]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

# 20 Inbuilt function In Pandas

In [48]:
import pandas as pd

# 1 Head

In [114]:
df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
                   'monkey', 'parrot', 'shark', 'whale', 'zebra']})
df

animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

In [115]:
df.head()

animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey

# 2 df.query

In [116]:
df = pd.DataFrame({'A': range(1, 6),
                   'B': range(10, 0, -2),
                   'C C': range(10, 5, -1)})
df

A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6

In [117]:
df.query('A > B')

A  B  C C
4  5  2    6

# 3 df.agg 

In [120]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df.agg(['sum', 'min'])

A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

# 4 df.iloc

In [121]:
mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000 }]
df = pd.DataFrame(mydict)
df

a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

In [122]:
type(df.iloc[0])

pandas.core.series.Series

In [123]:
df.iloc[0]

a    1
b    2
c    3
d    4
Name: 0, dtype: int64

# 5 df.loc

In [124]:
df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
     index=['cobra', 'viper', 'sidewinder'],
     columns=['max_speed', 'shield'])
df

max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

In [125]:
df.loc['viper']

max_speed    4
shield       5
Name: viper, dtype: int64

# 6  df[‘’].dtypes

In [126]:
df = pd.DataFrame({'float': [1.0],
                   'int': [1],
                   'datetime': [pd.Timestamp('20180310')],
                   'string': ['foo']})
df.dtypes

float              float64
int                  int64
datetime    datetime64[ns]
string              object
dtype: object

# 7 df.cov()

In [127]:
df = pd.DataFrame([(1, 2), (0, 3), (2, 0), (1, 1)],
                  columns=['dogs', 'cats'])
df.cov()

dogs      cats
dogs  0.666667 -1.000000
cats -1.000000  1.666667

# 8 df[‘’].cumsum()

In [128]:
s = pd.Series([2, np.nan, 5, -1, 0])
s

0    2.0
1    NaN
2    5.0
3   -1.0
4    0.0
dtype: float64

# 9 Data frame

In [93]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

# 10 df.info

In [94]:
int_values = [1, 2, 3, 4, 5]
text_values = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']
float_values = [0.0, 0.25, 0.5, 0.75, 1.0]
df = pd.DataFrame({"int_col": int_values, "text_col": text_values,
                  "float_col": float_values})
df

int_col text_col  float_col
0        1    alpha       0.00
1        2     beta       0.25
2        3    gamma       0.50
3        4    delta       0.75
4        5  epsilon       1.00

# 11 df.values

In [96]:
df = pd.DataFrame({'age':    [ 3,  29],
                   'height': [94, 170],
                   'weight': [31, 115]})
df
   

age  height  weight
0    3      94      31
1   29     170     115

In [97]:
df.dtypes

age       int64
height    int64
weight    int64
dtype: object

In [98]:
df.values

array([[  3,  94,  31],
       [ 29, 170, 115]], dtype=int64)

# 12 df.axes

In [99]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df.axes

[RangeIndex(start=0, stop=2, step=1), Index(['col1', 'col2'], dtype='object')]

# 13 df.ndim

In [100]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df.ndim

2

# 14 df.size

In [101]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df.size

4

# 15 df.shape

In [102]:
df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
df.shape

(2, 2)

# 16 df.empty

In [103]:
df_empty = pd.DataFrame({'A' : []})
df_empty

Empty DataFrame
Columns: [A]
Index: []

In [104]:
df_empty.empty

True

# 17 df.set_flags

In [105]:
df = pd.DataFrame({"A": [1, 2]})
df.flags.allows_duplicate_labels

True

In [106]:
df2 = df.set_flags(allows_duplicate_labels=False)
df2.flags.allows_duplicate_labels

False

# 18 df.astype

In [107]:
ser = pd.Series([1, 2], dtype='int32')
ser

0    1
1    2
dtype: int32

In [108]:
ser.astype('int64')

0    1
1    2
dtype: int64

# 19 df.bool

In [109]:
pd.Series([True]).bool()

True

In [110]:
pd.Series([False]).bool()

False

# 20 df.at

In [111]:
df = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]],
                  index=[4, 5, 6], columns=['A', 'B', 'C'])
df

A   B   C
4   0   2   3
5   0   4   1
6  10  20  30

In [112]:
df.at[4, 'B']

2