Research and write down 20 in built method on pandas and 20 on numpy with examples each.


In [1]:
import numpy as np
import pandas as pd
import random

Numpy Inbuilt Methods

In [2]:
#1. zeros() - create arrays of zeros (0)
arr_zero =np.zeros((5,6), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [3]:
#2. ones() - create arrays of ones (1)
arr_ones = np.ones((5,6), dtype=float)
arr_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
#3. array() - create arrays
my_arr = np.array([10, 20, 30, 40, 50, 60, 70])
my_arr

array([10, 20, 30, 40, 50, 60, 70])

In [5]:
#4. type() - shows the type of object in array
type(my_arr)

numpy.ndarray

In [6]:
#5. append() - add new elements to an array
new_myarr = np.append(my_arr, [80,90,100])
new_myarr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
#6. reshape() 
b_arr = new_myarr.reshape(2,5)
b_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [8]:
#7. shape()
b_arr.shape

(2, 5)

In [9]:
#8. linspace() - returns evenly spaced numbers inclusive of the range number.
l_arr =np.linspace(0, 30, 50)
l_arr

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [10]:
#9. concatenate() - used to join arrays
c_arr = np.array([200, 300, 400, 500, 600])

arr = np.concatenate((new_myarr, c_arr))
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 200, 300, 400,
       500, 600])

In [11]:
#10. max() - returns maximum element
arr.max()

600

In [12]:
#11. min() - returns minimum element
arr.min()

10

In [13]:
#12. mean _ returns the mean value of the array set
arr.mean()

170.0

In [14]:
#13. ndim() - checks the array dimension
arr.ndim

1

In [15]:
#14. vstack() - vertical stacking of arrays( also used to join arrays by adding along columns)
d_arr = np.array([1,2,3,4,5, 6,7])
v_arr = np.vstack((my_arr, d_arr))
v_arr

array([[10, 20, 30, 40, 50, 60, 70],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [16]:
d_arr = np.array([1,2,3,4,5, 6,7])
v_arr = np.vstack(((my_arr.reshape(-1,1)), d_arr.reshape(-1, 1)))
v_arr

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7]])

In [17]:
#15. hstack() - stacking arrays along rows
h_arr = np.hstack((my_arr, d_arr))
h_arr

array([10, 20, 30, 40, 50, 60, 70,  1,  2,  3,  4,  5,  6,  7])

In [18]:
d_arr = np.array([1,2,3,4,5, 6,7])
h_arr = np.hstack(((my_arr.reshape(-1,1)), d_arr.reshape(-1, 1)))
h_arr

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5],
       [60,  6],
       [70,  7]])

In [19]:
#16. transpose()
np.transpose(b_arr)

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [20]:
#17. sum() - sum up elements in the array
np.sum(arr)

2550

In [21]:
arr.sum()

2550

In [22]:
#18. cumsum() - cummulative addition of the elements in the array
np.cumsum(arr)

array([  10,   30,   60,  100,  150,  210,  280,  360,  450,  550,  750,
       1050, 1450, 1950, 2550], dtype=int32)

In [23]:
arr.cumsum()

array([  10,   30,   60,  100,  150,  210,  280,  360,  450,  550,  750,
       1050, 1450, 1950, 2550], dtype=int32)

In [24]:
#19. eye()
np.eye(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
#20. array_split()
np.array_split(arr, 5)

[array([10, 20, 30]),
 array([40, 50, 60]),
 array([70, 80, 90]),
 array([100, 200, 300]),
 array([400, 500, 600])]

Pandas Inbuilt Methods

In [26]:
#1. Series()
names = ["Bisi", "John", "Mary", "Abdul", "Ope" ]
new_ser = pd.Series(data= c_arr, index = names)
new_ser

Bisi     200
John     300
Mary     400
Abdul    500
Ope      600
dtype: int32

In [27]:
new_ser = pd.Series(c_arr, names)
new_ser

Bisi     200
John     300
Mary     400
Abdul    500
Ope      600
dtype: int32

In [28]:
#2. count()
new_ser.count()

5

In [29]:
#3. keys() - return alias for index
new_ser.keys()

Index(['Bisi', 'John', 'Mary', 'Abdul', 'Ope'], dtype='object')

In [30]:
#4. index
new_ser.index

Index(['Bisi', 'John', 'Mary', 'Abdul', 'Ope'], dtype='object')

In [31]:
#5. len()
len(new_ser)

5

In [32]:
#6. agg()
new_ser.agg((min, max))

min    200
max    600
dtype: int64

In [70]:
#7. Dataframe()
new = [1,2,3,4,5]
df = pd.DataFrame(new_ser)
df

0
Bisi   200
John   300
Mary   400
Abdul  500
Ope    600

In [71]:
#8.type()
type(df)

pandas.core.frame.DataFrame

In [72]:
#9. to.frame()
df1 = new_ser.to_frame()
df1

0
Bisi   200
John   300
Mary   400
Abdul  500
Ope    600

In [73]:
#10. rename()
df = df.rename(columns = {0: "Amount"})
df

Amount
Bisi      200
John      300
Mary      400
Abdul     500
Ope       600

In [74]:
#11. reset_index() 
df = df.reset_index()
df

index  Amount
0   Bisi     200
1   John     300
2   Mary     400
3  Abdul     500
4    Ope     600

In [75]:
df = df.rename(columns = {"index": "Name"})
df

Name  Amount
0   Bisi     200
1   John     300
2   Mary     400
3  Abdul     500
4    Ope     600

In [76]:
#12. assign() - 
df = df.assign(location=["Lagos", "Abeokuta", "Sango", "Oyo", "Ilorin"])
df

Name  Amount  location
0   Bisi     200     Lagos
1   John     300  Abeokuta
2   Mary     400     Sango
3  Abdul     500       Oyo
4    Ope     600    Ilorin

In [77]:
#13. insert()
df.insert(0, "Reg_no", ["A01", "A02", "A03", "A04", "A05"], True)
df

Reg_no   Name  Amount  location
0    A01   Bisi     200     Lagos
1    A02   John     300  Abeokuta
2    A03   Mary     400     Sango
3    A04  Abdul     500       Oyo
4    A05    Ope     600    Ilorin

In [79]:
#14. ndim()
df.ndim

2

In [81]:
#15. count()
df.count()

Reg_no      5
Name        5
Amount      5
location    5
dtype: int64

In [82]:
#16. head()
df.head(3)

Reg_no  Name  Amount  location
0    A01  Bisi     200     Lagos
1    A02  John     300  Abeokuta
2    A03  Mary     400     Sango

In [83]:
#17. tail()
df.tail(3)

Reg_no   Name  Amount location
2    A03   Mary     400    Sango
3    A04  Abdul     500      Oyo
4    A05    Ope     600   Ilorin

In [85]:
#18. drop()
df.drop([2,3])

Reg_no  Name  Amount  location
0    A01  Bisi     200     Lagos
1    A02  John     300  Abeokuta
4    A05   Ope     600    Ilorin

In [86]:
#19. sort_values()
df.sort_values(by=['Name'])

Reg_no   Name  Amount  location
3    A04  Abdul     500       Oyo
0    A01   Bisi     200     Lagos
1    A02   John     300  Abeokuta
2    A03   Mary     400     Sango
4    A05    Ope     600    Ilorin

In [87]:
#20. info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Reg_no    5 non-null      object
 1   Name      5 non-null      object
 2   Amount    5 non-null      int32 
 3   location  5 non-null      object
dtypes: int32(1), object(3)
memory usage: 268.0+ bytes
