Research and write down 20 in built method on pandas and 20 on numpy with examples each.


In [1]:
import numpy as np
import pandas as pd
import random

Numpy Inbuilt Methods

In [2]:
#1. zeros() - create arrays of zeros (0)
arr_zero =np.zeros((5,6), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [3]:
#2. ones() - create arrays of ones (1)
arr_ones = np.ones((5,6), dtype=float)
arr_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [4]:
#3. array() - create arrays
my_arr = np.array([10, 20, 30, 40, 50, 60, 70])
my_arr

array([10, 20, 30, 40, 50, 60, 70])

In [5]:
#4. type() - shows the type of object in array
type(my_arr)

numpy.ndarray

In [6]:
#5. append() - add new elements to an array
new_myarr = np.append(my_arr, [80,90,100])
new_myarr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
#6. reshape() 
b_arr = new_myarr.reshape(2,5)
b_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [8]:
#7. shape()
b_arr.shape

(2, 5)

In [9]:
#8. linspace() - returns evenly spaced numbers inclusive of the range number.
l_arr =np.linspace(0, 30, 50)
l_arr

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [10]:
#9. concatenate() - used to join arrays
c_arr = np.array([200, 300, 400, 500, 600])

arr = np.concatenate((new_myarr, c_arr))
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 200, 300, 400,
       500, 600])

In [11]:
#10. max() - returns maximum element
arr.max()

600

In [12]:
#11. min() - returns minimum element
arr.min()

10

In [13]:
#12. mean _ returns the mean value of the array set
arr.mean()

170.0

In [14]:
#13. ndim() - checks the array dimension
arr.ndim

1

In [15]:
#14. vstack() - vertical stacking of arrays( also used to join arrays by adding along columns)
d_arr = np.array([1,2,3,4,5, 6,7])
v_arr = np.vstack((my_arr, d_arr))
v_arr

array([[10, 20, 30, 40, 50, 60, 70],
       [ 1,  2,  3,  4,  5,  6,  7]])

In [16]:
d_arr = np.array([1,2,3,4,5, 6,7])
v_arr = np.vstack(((my_arr.reshape(-1,1)), d_arr.reshape(-1, 1)))
v_arr

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7]])

In [17]:
#15. hstack() - stacking arrays along rows
h_arr = np.hstack((my_arr, d_arr))
h_arr

array([10, 20, 30, 40, 50, 60, 70,  1,  2,  3,  4,  5,  6,  7])

In [18]:
d_arr = np.array([1,2,3,4,5, 6,7])
h_arr = np.hstack(((my_arr.reshape(-1,1)), d_arr.reshape(-1, 1)))
h_arr

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5],
       [60,  6],
       [70,  7]])

In [19]:
#16. transpose()
np.transpose(b_arr)

array([[ 10,  60],
       [ 20,  70],
       [ 30,  80],
       [ 40,  90],
       [ 50, 100]])

In [20]:
#17. sum() - sum up elements in the array
np.sum(arr)

2550

In [21]:
arr.sum()

2550

In [22]:
#18. cumsum() - cummulative addition of the elements in the array
np.cumsum(arr)

array([  10,   30,   60,  100,  150,  210,  280,  360,  450,  550,  750,
       1050, 1450, 1950, 2550], dtype=int32)

In [23]:
arr.cumsum()

array([  10,   30,   60,  100,  150,  210,  280,  360,  450,  550,  750,
       1050, 1450, 1950, 2550], dtype=int32)

In [24]:
#19. eye()
np.eye(5, dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
#20. array_split()
np.array_split(arr, 5)

[array([10, 20, 30]),
 array([40, 50, 60]),
 array([70, 80, 90]),
 array([100, 200, 300]),
 array([400, 500, 600])]

Pandas Inbuilt Methods

In [36]:
#1. Series()
names = ["Bisi", "John", "Mary", "Abdul", "Ope" ]
new_ser = pd.Series(data= c_arr, index = names)
new_ser

Bisi     200
John     300
Mary     400
Abdul    500
Ope      600
dtype: int32

In [44]:
new_ser = pd.Series(c_arr, names)
new_ser

Bisi     200
John     300
Mary     400
Abdul    500
Ope      600
dtype: int32

In [55]:
#2. count()
new_ser.count()

5

In [64]:
#3.
