 METHODS IN NUMPY


In [4]:
import numpy as np

In [7]:
#zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#ones
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [12]:
#arange
np.arange(1,5)

array([1, 2, 3, 4])

In [13]:
#linspace()
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [14]:
#reshape()
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
#sin()
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [19]:
#exp()
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [21]:
#min()
a = [10,30,26,90,19]
np.min(a)

10

In [22]:
#max()
np.max(a)

90

In [23]:
#vstack
a = [[1,2,5,7], [7,9,10,6]]
np.vstack(a)

array([[ 1,  2,  5,  7],
       [ 7,  9, 10,  6]])

In [24]:
#hstack
np.hstack(a)

array([ 1,  2,  5,  7,  7,  9, 10,  6])

In [32]:
#copy()
arr = np.array([1,2,3,4,6])
x = arr.copy()
arr[0] = 45
print(arr)
print(x)

[45  2  3  4  6]
[1 2 3 4 6]


In [33]:
#view()
y= arr.view()
arr[1]= 26
print(arr)
print(y)

[45 26  3  4  6]
[45 26  3  4  6]


In [34]:
arr = np.array([3,5,7,9,11])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)               #base() to check if the copy owns the data

None
[ 3  5  7  9 11]


In [35]:
#concatenate
arr1 = np.array([10,30,50])
arr2 = ([6,5,4])

arr = np.concatenate((arr1, arr2))
print(arr)

[10 30 50  6  5  4]


In [36]:
#sort
arr = np.array([2,8,5,100])
print(np.sort(arr))

[  2   5   8 100]


In [38]:
#array_split()
data = np.array([1,3,5,7,9,11])
newdata = np.array_split(data, 3)
print(newdata)

[array([1, 3]), array([5, 7]), array([ 9, 11])]


In [39]:
#where()
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr ==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [40]:
#searchsorted()
arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

1


In [42]:
#choice()
from numpy import random
x = random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size =(3,5))
print(x)

[[7 5 7 7 7]
 [5 7 7 5 7]
 [7 3 3 7 5]]


In [43]:
#astype()
arr = np.array([1.1, 2.1, 3.1])
newarr =arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


### METHODS IN PANDAS

In [44]:
import pandas as pd

In [45]:
fileName = 'WorldHappiness_Corruption.csv'
filePath = 'C:\Kaggle dataset'

In [46]:
#read_csv()
filePathDir = filePath + '/' + fileName
df = pd.read_csv(filePathDir)

In [47]:
df

Country  happiness_score  gdp_per_capita    family    health  \
0         Norway           7.5370        1.616463  1.533524  0.796667   
1        Denmark           7.5220        1.482383  1.551122  0.792566   
2        Iceland           7.5040        1.480633  1.610574  0.833552   
3    Switzerland           7.4940        1.564980  1.516912  0.858131   
4        Finland           7.4690        1.443572  1.540247  0.809158   
..           ...              ...             ...       ...       ...   
787     Botswana           3.4789        0.997549  0.000000  0.494102   
788     Tanzania           3.4762        0.457163  0.000000  0.442678   
789       Rwanda           3.3123        0.343243  0.000000  0.572383   
790     Zimbabwe           3.2992        0.425564  0.000000  0.375038   
791  Afghanistan           2.5669        0.300706  0.000000  0.266052   

      freedom  generosity  government_trust  dystopia_residual continent  \
0    0.635423    0.362012          0.315964           2.277027    Europe   
1    0.626007    0.355280          0.400770           2.313707    Europe   
2    0.627163    0.475540          0.153527           2.322715    Europe   
3    0.620071    0.290549          0.367007           2.276716    Europe   
4    0.617951    0.245483          0.382612           2.430182    Europe   
..        ...         ...               ...                ...       ...   
787  0.509089    0.033407          0.101786           0.257241    Africa   
788  0.509343    0.271541          0.203881           0.718963    Africa   
789  0.604088    0.235705          0.485542           0.548445    Africa   
790  0.377405    0.151349          0.080929           0.841031    Africa   
791  0.000000    0.135235          0.001226           1.507236      Asia   

     Year  social_support  cpi_score  
0    2015        0.000000         88  
1    2015        0.000000         91  
2    2015        0.000000         79  
3    2015        0.000000         86  
4    2015        0.000000         90  
..    ...             ...        ...  
787  2020        1.085695         60  
788  2020        0.872675         38  
789  2020        0.522876         54  
790  2020        1.047835         24  
791  2020        0.356434         19  

[792 rows x 13 columns]

In [71]:
#head
filePathDir = filePath + '/' + fileName
df = pd.read_csv(filePathDir)
df.head()

Country  happiness_score  gdp_per_capita    family    health   freedom  \
0       Norway            7.537        1.616463  1.533524  0.796667  0.635423   
1      Denmark            7.522        1.482383  1.551122  0.792566  0.626007   
2      Iceland            7.504        1.480633  1.610574  0.833552  0.627163   
3  Switzerland            7.494        1.564980  1.516912  0.858131  0.620071   
4      Finland            7.469        1.443572  1.540247  0.809158  0.617951   

   generosity  government_trust  dystopia_residual continent  Year  \
0    0.362012          0.315964           2.277027    Europe  2015   
1    0.355280          0.400770           2.313707    Europe  2015   
2    0.475540          0.153527           2.322715    Europe  2015   
3    0.290549          0.367007           2.276716    Europe  2015   
4    0.245483          0.382612           2.430182    Europe  2015   

   social_support  cpi_score  
0             0.0         88  
1             0.0         91  
2             0.0         79  
3             0.0         86  
4             0.0         90

In [49]:
#describe
df.describe

<bound method NDFrame.describe of          Country  happiness_score  gdp_per_capita    family    health  \
0         Norway           7.5370        1.616463  1.533524  0.796667   
1        Denmark           7.5220        1.482383  1.551122  0.792566   
2        Iceland           7.5040        1.480633  1.610574  0.833552   
3    Switzerland           7.4940        1.564980  1.516912  0.858131   
4        Finland           7.4690        1.443572  1.540247  0.809158   
..           ...              ...             ...       ...       ...   
787     Botswana           3.4789        0.997549  0.000000  0.494102   
788     Tanzania           3.4762        0.457163  0.000000  0.442678   
789       Rwanda           3.3123        0.343243  0.000000  0.572383   
790     Zimbabwe           3.2992        0.425564  0.000000  0.375038   
791  Afghanistan           2.5669        0.300706  0.000000  0.266052   

      freedom  generosity  government_trust  dystopia_residual continent  \
0    0.635423

In [50]:
#Transpose
df.describe().T

count         mean        std        min          25%  \
happiness_score    792.0     5.473310   1.124726     2.5669     4.590750   
gdp_per_capita     792.0     0.929217   0.385774     0.0000     0.644242   
family             792.0     0.504998   0.552736     0.0000     0.000000   
health             792.0     0.648691   0.232261     0.0000     0.510070   
freedom            792.0     0.427016   0.148003     0.0000     0.325433   
generosity         792.0     0.212440   0.121660     0.0000     0.125784   
government_trust   792.0     0.125720   0.109032     0.0000     0.052862   
dystopia_residual  792.0     1.379277   1.075276     0.0000     0.000000   
Year               792.0  2017.500000   1.708904  2015.0000  2016.000000   
social_support     792.0     0.609302   0.640754     0.0000     0.000000   
cpi_score          792.0    44.327020  19.508833    11.0000    30.000000   

                           50%          75%          max  
happiness_score       5.485500     6.300500     7.808700  
gdp_per_capita        0.994544     1.228677     2.096000  
family                0.000000     1.040410     1.610574  
health                0.685397     0.815641     1.141000  
freedom               0.439621     0.546280     0.724000  
generosity            0.197000     0.273250     0.838075  
government_trust      0.089000     0.154250     0.551910  
dystopia_residual     1.731948     2.236894     3.602140  
Year               2017.500000  2019.000000  2020.000000  
social_support        0.176214     1.268250     1.644000  
cpi_score            38.000000    57.000000    91.000000

In [51]:
#memory_usage
df.memory_usage()

Index                 128
Country              6336
happiness_score      6336
gdp_per_capita       6336
family               6336
health               6336
freedom              6336
generosity           6336
government_trust     6336
dystopia_residual    6336
continent            6336
Year                 6336
social_support       6336
cpi_score            6336
dtype: int64

In [52]:
#info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Country            792 non-null    object 
 1   happiness_score    792 non-null    float64
 2   gdp_per_capita     792 non-null    float64
 3   family             792 non-null    float64
 4   health             792 non-null    float64
 5   freedom            792 non-null    float64
 6   generosity         792 non-null    float64
 7   government_trust   792 non-null    float64
 8   dystopia_residual  792 non-null    float64
 9   continent          792 non-null    object 
 10  Year               792 non-null    int64  
 11  social_support     792 non-null    float64
 12  cpi_score          792 non-null    int64  
dtypes: float64(9), int64(2), object(2)
memory usage: 80.6+ KB


In [56]:
#astype
df["social_support"] =df['social_support'].astype(int)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 792 entries, 0 to 791
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Country            792 non-null    object 
 1   happiness_score    792 non-null    float64
 2   gdp_per_capita     792 non-null    float64
 3   family             792 non-null    float64
 4   health             792 non-null    float64
 5   freedom            792 non-null    float64
 6   generosity         792 non-null    float64
 7   government_trust   792 non-null    float64
 8   dystopia_residual  792 non-null    float64
 9   continent          792 non-null    object 
 10  Year               792 non-null    int64  
 11  social_support     792 non-null    int32  
 12  cpi_score          792 non-null    int64  
dtypes: float64(8), int32(1), int64(2), object(2)
memory usage: 77.5+ KB
None


In [57]:
#loc
df.loc[0:3, ['Country', 'happiness_score']]

Country  happiness_score
0       Norway            7.537
1      Denmark            7.522
2      Iceland            7.504
3  Switzerland            7.494

In [66]:
#to_datetime
df1 = pd.DataFrame({'year':[2015,2016], 'month': [2,3], 'day': [4,5]})
pd.to_datetime(df1)

0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

In [73]:
#value_counts()
df['Year'].value_counts()

2015    132
2016    132
2017    132
2018    132
2019    132
2020    132
Name: Year, dtype: int64

In [76]:
#drop_duplicates()
df.drop_duplicates(inplace=True)
df

#no duplicates in the dat

Country  happiness_score  gdp_per_capita    family    health  \
0         Norway           7.5370        1.616463  1.533524  0.796667   
1        Denmark           7.5220        1.482383  1.551122  0.792566   
2        Iceland           7.5040        1.480633  1.610574  0.833552   
3    Switzerland           7.4940        1.564980  1.516912  0.858131   
4        Finland           7.4690        1.443572  1.540247  0.809158   
..           ...              ...             ...       ...       ...   
787     Botswana           3.4789        0.997549  0.000000  0.494102   
788     Tanzania           3.4762        0.457163  0.000000  0.442678   
789       Rwanda           3.3123        0.343243  0.000000  0.572383   
790     Zimbabwe           3.2992        0.425564  0.000000  0.375038   
791  Afghanistan           2.5669        0.300706  0.000000  0.266052   

      freedom  generosity  government_trust  dystopia_residual continent  \
0    0.635423    0.362012          0.315964           2.277027    Europe   
1    0.626007    0.355280          0.400770           2.313707    Europe   
2    0.627163    0.475540          0.153527           2.322715    Europe   
3    0.620071    0.290549          0.367007           2.276716    Europe   
4    0.617951    0.245483          0.382612           2.430182    Europe   
..        ...         ...               ...                ...       ...   
787  0.509089    0.033407          0.101786           0.257241    Africa   
788  0.509343    0.271541          0.203881           0.718963    Africa   
789  0.604088    0.235705          0.485542           0.548445    Africa   
790  0.377405    0.151349          0.080929           0.841031    Africa   
791  0.000000    0.135235          0.001226           1.507236      Asia   

     Year  social_support  cpi_score  
0    2015        0.000000         88  
1    2015        0.000000         91  
2    2015        0.000000         79  
3    2015        0.000000         86  
4    2015        0.000000         90  
..    ...             ...        ...  
787  2020        1.085695         60  
788  2020        0.872675         38  
789  2020        0.522876         54  
790  2020        1.047835         24  
791  2020        0.356434         19  

[792 rows x 13 columns]

In [77]:
#groupby()
df.groupby(by='continent').family.mean()

continent
Africa           0.403690
Asia             0.471045
Australia        0.663723
Europe           0.590485
North America    0.580827
South America    0.540228
Name: family, dtype: float64

In [80]:
#merge()
table1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'], 'value':[1,2,3,5]})
table2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'], 'value':[5,6,7,8]})
table1.merge(table2, left_on='lkey', right_on='rkey')

lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

In [86]:
#sort_values()
print(df.sort_values(by='Country', inplace=False).T)

                           395          657          519          259  \
Country            Afghanistan  Afghanistan  Afghanistan  Afghanistan   
happiness_score          3.203         3.36        3.632        3.575   
gdp_per_capita            0.35      0.38227        0.332      0.31982   
family                     0.0      0.11037          0.0      0.30285   
health                   0.361      0.17344        0.255      0.30335   
freedom                    0.0       0.1643        0.085      0.23414   
generosity               0.158      0.31268        0.191       0.3651   
government_trust         0.025      0.07112        0.036      0.09719   
dystopia_residual          0.0      2.14558          0.0       1.9521   
continent                 Asia         Asia         Asia         Asia   
Year                      2017         2019         2018         2016   
social_support           0.517          0.0        0.537          0.0   
cpi_score                   15           16        

In [87]:
#tail
df.tail()

Country  happiness_score  gdp_per_capita    family    health   freedom  \
119  Zimbabwe           3.8750        0.375847  1.083096  0.196764  0.336384   
388  Zimbabwe           3.6630        0.366000  0.000000  0.433000  0.361000   
790  Zimbabwe           3.2992        0.425564  0.000000  0.375038  0.377405   
518  Zimbabwe           3.6920        0.357000  0.000000  0.248000  0.406000   
639  Zimbabwe           4.1930        0.350410  0.714780  0.159500  0.254290   

     generosity  government_trust  dystopia_residual continent  Year  \
119    0.189143          0.095375           1.597970    Africa  2015   
388    0.151000          0.089000           0.000000    Africa  2017   
790    0.151349          0.080929           0.841031    Africa  2020   
518    0.132000          0.099000           0.000000    Africa  2018   
639    0.185030          0.085820           2.442700    Africa  2019   

     social_support  cpi_score  
119        0.000000         21  
388        1.114000         22  
790        1.047835         24  
518        1.094000         22  
639        0.000000         24

In [89]:
#shape
df.shape

(792, 13)

In [90]:
#sample
df.sample(n=8)

Country  happiness_score  gdp_per_capita    family    health   freedom  \
340   Nigeria           5.2650        0.696000  0.000000  0.245000  0.426000   
31      Spain           6.4030        1.384398  1.532091  0.888961  0.408781   
49    Moldova           5.8380        0.728871  1.251826  0.589465  0.240729   
370   Tunisia           4.4610        0.921000  0.000000  0.815000  0.167000   
245  Bulgaria           4.2180        1.012160  1.106140  0.766490  0.305870   
43      Italy           5.9640        1.395067  1.444923  0.853144  0.256451   
781   Burundi           3.7753        0.000000  0.000000  0.295213  0.275399   
136    Canada           7.4270        1.326290  1.322610  0.905630  0.632970   

     generosity  government_trust  dystopia_residual      continent  Year  \
340    0.215000          0.041000           0.000000         Africa  2017   
31     0.190134          0.070914           1.927758         Europe  2015   
49     0.208779          0.010091           2.807808         Europe  2015   
370    0.059000          0.055000           0.000000         Africa  2017   
245    0.119210          0.008720           0.899910         Europe  2016   
43     0.172790          0.028028           1.813312         Europe  2015   
781    0.187402          0.212187           2.401507         Africa  2020   
136    0.458110          0.329570           2.451760  North America  2016   

     social_support  cpi_score  
340        1.111000         27  
31         0.000000         58  
49         0.000000         33  
370        1.000000         42  
245        0.000000         41  
43         0.000000         44  
781        0.403575         19  
136        0.000000         82

In [91]:
#df.isnull().sum()
df.isnull().sum()

Country              0
happiness_score      0
gdp_per_capita       0
family               0
health               0
freedom              0
generosity           0
government_trust     0
dystopia_residual    0
continent            0
Year                 0
social_support       0
cpi_score            0
dtype: int64

In [92]:
#nunique()
df.nunique()

Country              132
happiness_score      747
gdp_per_capita       767
family               396
health               733
freedom              734
generosity           707
government_trust     682
dystopia_residual    529
continent              6
Year                   6
social_support       360
cpi_score             77
dtype: int64

METHOD 20 #Query

In [93]:
df.query('3 < happiness_score < 8')[:10]

Country  happiness_score  gdp_per_capita    family    health  \
395  Afghanistan           3.2030        0.350000  0.000000  0.361000   
657  Afghanistan           3.3600        0.382270  0.110370  0.173440   
519  Afghanistan           3.6320        0.332000  0.000000  0.255000   
259  Afghanistan           3.5750        0.319820  0.302850  0.303350   
120  Afghanistan           3.7940        0.401477  0.581543  0.180747   
493      Albania           4.5860        0.916000  0.000000  0.790000   
753      Albania           4.8827        0.906653  0.000000  0.846330   
96       Albania           4.6440        0.996193  0.803685  0.731160   
620      Albania           4.6550        0.955300  0.501630  0.730070   
213      Albania           4.9590        0.878670  0.804340  0.813250   

      freedom  generosity  government_trust  dystopia_residual continent  \
395  0.000000    0.158000          0.025000           0.000000      Asia   
657  0.164300    0.312680          0.071120           2.145580      Asia   
519  0.085000    0.191000          0.036000           0.000000      Asia   
259  0.234140    0.365100          0.097190           1.952100      Asia   
120  0.106180    0.311871          0.061158           2.150801      Asia   
493  0.419000    0.149000          0.032000           0.000000    Europe   
753  0.461946    0.171028          0.025361           1.640897    Europe   
96   0.381499    0.201313          0.039864           1.490442    Europe   
620  0.318660    0.168400          0.053010           1.928160    Europe   
213  0.357330    0.142720          0.064130           1.898940    Europe   

     Year  social_support  cpi_score  
395  2017        0.517000         15  
657  2019        0.000000         16  
519  2018        0.537000         16  
259  2016        0.000000         15  
120  2015        0.000000         11  
493  2018        0.817000         36  
753  2020        0.830484         36  
96   2015        0.000000         36  
620  2019        0.000000         35  
213  2016        0.000000         39