#20 in-buitlt method in Numpy

In [45]:
import numpy as np
import pandas as pd

In [4]:
#1.np.repeat
#This function repeats the elements of an array
#The number of repititions is specified by the second argument
#repeat string "Aminat" 6 times
np.repeat("Aminat", 6)

array(['Aminat', 'Aminat', 'Aminat', 'Aminat', 'Aminat', 'Aminat'],
      dtype='<U6')

In [14]:
#2.np.random.random
#This function generates n random float samples
#generate 5 float samples
np.random.random(5)

array([0.94261659, 0.02651446, 0.36582488, 0.90301842, 0.96778382])

In [18]:
#3.np.full
#This function creates an n dimensional array of a random value
#create a 4 by 6 dimensional array of 2
fill_value=random value to fill inside the array
np.full((4,6),fill_value=2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [20]:
#4.np.identity
#This function creates an indentity matrix with 1s on its main diagonal
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
#5.np.mean
#This function is used to get the mean of the array
x= np.array([[2,4,6],[8,10,12]])
np.mean(x)

7.0

In [25]:
#6.np.median
#This function returns the median value of the array
y=np.array([[2,3,4],[7,8,9]])
np.median(y)

5.5

In [28]:
#7.np.digitize
#This function returns the indices of the bins to which each value in the input array belongs
a=np.array([0.5, 1.4, 2.2, 3.6, 4.1, 5.8])
bins=np.array([0,1,2,3,4])
np.digitize(a,bins)

array([1, 2, 3, 4, 5, 5], dtype=int64)

In [9]:
#8.np.expand_dims
#This function is used to expand the dimensions of an array
A = np.array([ 2, 12, 22, 1, 11, 3, 13, 33, 4, 14, 44 ])
np.expand_dims(A,axis=1)


array([[ 2],
       [12],
       [22],
       [ 1],
       [11],
       [ 3],
       [13],
       [33],
       [ 4],
       [14],
       [44]])

In [10]:
#9.np.squeeze
#This function reduces the dimension of an array by removing single-dimensional entries
A = ([[2], [4], [6], [8], [10], [12]])
np.squeeze(A)

array([ 2,  4,  6,  8, 10, 12])

In [11]:
# 10.np.count_nonzero
#This function counts all the non-zero elements and returns their count
B = ([1, 0, 6, 8, 0, 5, 0, 7, 5, 0])
np.count_nonzero(B)

6

In [15]:
#11.np.argwhere
#This function finds and returns all the indices of non-zero elements
A = np.array([1, 0, 0, 1, 0, 0])
np.argwhere(A)


array([[0],
       [3]], dtype=int64)

In [16]:
#12.np.sort
#This function sorts the array and returns it
A = np.array([15, 5, 25, 20, 10])
np.sort(A)

array([ 5, 10, 15, 20, 25])

In [17]:
#13.np.abs
#This function returns the absolute values of elements inside an array
Y = ([[1, -1, -2, 6], [-3, 8, 9, 7], [-8, 9,-4, 8]])
np.abs(Y)

array([[1, 1, 2, 6],
       [3, 8, 9, 7],
       [8, 9, 4, 8]])

In [20]:
#14. np.round
#This function rounds the float values to a specified number of decimal points
a = np.random.random (size = (3,3))
a

array([[0.21088777, 0.105069  , 0.99399229],
       [0.84147761, 0.70617577, 0.0140658 ],
       [0.96821927, 0.0063042 , 0.52097957]])

In [22]:
#to round the float values to zero decimal point
np.round(a, decimals=0)

array([[0., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.]])

In [24]:
#15.np.clip
#This function is used to keep the values of an array within a range
X = np.array([1, -2, 5, 6, -7, 8, 9, 4, 6])
X.clip(1,7)

array([1, 1, 5, 6, 1, 7, 7, 4, 6])

In [32]:
#16.np.put
#This function replaces specified elements of an array with given values
arr= np.array([2,4,6,8,10,12])
arr


array([ 2,  4,  6,  8, 10, 12])

In [35]:
np.put(arr,[0,2,4], [1,3,9])
arr

array([ 1,  4,  3,  8,  9, 12])

In [37]:
#17.np.copyto
#This function is used to copy the contents of one array into another
X = np.array([1,2,3])
Y = np.array([4,5,6])
np.copyto(X,Y)
X

array([4, 5, 6])

In [40]:
#18.np.setdiff1d
#This function returns all the unique elements in array 1 that are not present in array 2
A = np.array([1,2,3,1,5,8,7,8])
B = np.array([1,9,2,4,6,7,1,2])
np.setdiff1d(A,B)

array([3, 5, 8])

In [41]:
#19.np.setxor1d
#This function returns all the unique values from both arrays in sorted order
A = np.array([1,2,4,6,7,8])
B = np.array([1,2,3,5,8,9])
np.setxor1d(A,B)

array([3, 4, 5, 6, 7, 9])

In [42]:
#20.np.union1d
#This function combines both array into one
A = np.array([2,4,5,6])
B = np.array([1,2,3,4])
np.union1d(A,B)

array([1, 2, 3, 4, 5, 6])

#20 in-built method in pandas

In [56]:
#to create dataframe from scratch 
my_class = {"names" : ["Aminat", "Aishat", "Fatimah", "Zully", "Zainab"],
            "ages" : [15, 34, 23,14,20],
            "height" : [6.5, 5.5, 5, 6, 6]}
df = pd.DataFrame(my_class)
print(df)

     names  ages  height
0   Aminat    15     6.5
1   Aishat    34     5.5
2  Fatimah    23     5.0
3    Zully    14     6.0
4   Zainab    20     6.0


In [52]:
#1.Dtypes
#This function shows the type of data of each column
df.dtypes

names       object
ages         int64
heaight    float64
dtype: object

In [53]:
#2.data.shape
#This function shows the number of dimension as well as the size in each dimension
df.shape

(5, 3)

In [54]:
#3.data.size
#This function returns the size of a dataframe which is the number of rows multiplied by the number of columns
df.size

15

In [55]:
#4.data.describe
#This function does a quick statistical summary of numerical columns
df.describe

<bound method NDFrame.describe of      names  ages  heaight
0   Aminat    15      6.5
1   Aishat    34      5.5
2  Fatimah    23      5.0
3    Zully    14      6.0
4   Zainab    20      6.0>

In [61]:
#5.len()
#This function provides the length of the dataframe
len(df)

5

In [62]:
#6.df.iloc
#This function access row values
df.iloc[0:2]

names  ages  height
0  Aminat    15     6.5
1  Aishat    34     5.5

In [63]:
#7.df.replace()
#This function replaces the value of a column
df.replace(6.5, 6.1)

names  ages  height
0   Aminat    15     6.1
1   Aishat    34     5.5
2  Fatimah    23     5.0
3    Zully    14     6.0
4   Zainab    20     6.0

In [64]:
#8.df.rename()
#This function is used to rename colums
df.rename(columns = {"names": "Name", "ages": "Age", "height" : "Height"})

Name  Age  Height
0   Aminat   15     6.5
1   Aishat   34     5.5
2  Fatimah   23     5.0
3    Zully   14     6.0
4   Zainab   20     6.0

In [67]:
#9.df.count()
#This function provides the number of data in the dataframe in the specified direction
df.count(0)                  #counts the number of data in the columns

names     5
ages      5
height    5
dtype: int64

In [68]:
#10.df.columns
#This function is used to know the names of all the variables in a dataframe
df.columns

Index(['names', 'ages', 'height'], dtype='object')

In [69]:
#11.df.head()
#This function returns the first rows
df.head(3)                     #to return the first 3 rows

names  ages  height
0   Aminat    15     6.5
1   Aishat    34     5.5
2  Fatimah    23     5.0

In [70]:
#12.df.tail()
#This function returns the last rows
df.tail(2)                           #to return the last 2 rows

names  ages  height
3   Zully    14     6.0
4  Zainab    20     6.0

In [ ]:
#13.