# Numpy Inbuilt Methods

1) #numpy.linspace
This function returns evenly spaced numbers over a specified interval.

In [3]:
import numpy as np
import pandas as pd

In [39]:
#numpy.linspace
num=np.linspace(0,19,20) #start,stop,range
print(num)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


2) #numpy.repeat
This function repeats the elements of an array.

In [31]:
np.repeat(15,7) #The number of repetitions is specified by the second argument.

array([15, 15, 15, 15, 15, 15, 15])

3) #numpy.random.rand
This function returns random floats from the interval.

In [34]:
np.random.rand(6)

array([0.67972434, 0.18965819, 0.73479861, 0.3864146 , 0.315082  ,
       0.38704008])

4) #numpy.random.randint
This function returns random integers from the specified interval.

In [47]:
np.random.randint(4, size=6) 

array([3, 3, 2, 1, 3, 3])

5) #numpy.random.choice This function returns random sample from a given array.

In [49]:
np.random.choice([0,4], size=6)

array([0, 0, 4, 0, 0, 0])

6) #numpy.argmax This function returns the position of the maximum values along an axis.

In [56]:
num=np.array([[5,10,15,20],[25,30,35,40]])
max_num= np.argmax(num)
print(max_num)

7


7) #numpy.array This function creates an array.

In [71]:
num=[5,10,15,20,25,30]
arr=np.array(num)
type(arr)

numpy.ndarray

In [72]:
arr

array([ 5, 10, 15, 20, 25, 30])

8) #arr.shape This function shows the total number of indices in an array.

In [74]:
arr.shape

(6,)

9) #arr.reshape This function returns an array containing the same data with a new shape.

In [80]:
num1=[5,10,15,20,25,30]
num2=[2,4,6,8,10,12]
num3=[3,6,9,12,15,18]
num4=[4,8,12,16,20,24]
arr=np.array([num1,num2,num3,num4])
arr

array([[ 5, 10, 15, 20, 25, 30],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24]])

In [81]:
arr.shape

(4, 6)

In [83]:
arr.reshape(6,4)

array([[ 5, 10, 15, 20],
       [25, 30,  2,  4],
       [ 6,  8, 10, 12],
       [ 3,  6,  9, 12],
       [15, 18,  4,  8],
       [12, 16, 20, 24]])

10) #numpy.digitize This function is used to segregate many arrays into a group of arrays according to their values.

In [92]:
Age=np.array([12,24,36])
Group=np.array([1,2,3])
Bio=np.digitize(Age,Group)
print(Bio)

[3 3 3]


11) #numpy.arange This function is used to return evenly spaced values within a given interval.

In [96]:
arr=np.arange(0,10,step=1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr[3:9]

array([3, 4, 5, 6, 7, 8])

12) #numpy.ones This function returns a new array of given shape and type in the form of ones. 

In [99]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [104]:
np.ones((3,6,), dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

13) #numpy.zeros This function returns a new array of given shape and type in the form of zeros. 

In [105]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((5,10,), dtype=float)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

14) #numpy.random.randn 
This function returns random sample from a standard normal distribution.

In [111]:
num=np.random.randn(5,5)
num

array([[ 0.55918093, -0.47104053, -1.15303125,  0.29260571,  1.1976598 ],
       [ 0.12586893,  0.54446406, -1.0652639 , -1.18936381,  2.60892346],
       [ 0.32982191,  2.62350657, -0.13740828,  0.43308323,  0.02186395],
       [-0.48014548, -0.28448002,  0.50100668,  0.67213184, -0.85500154],
       [ 0.42911579, -0.41439164, -0.06714191, -0.9591153 ,  1.52765584]])

   15) #numpy.random.random_sample This function returns random floats in the half-open interval.

In [114]:
np.random.random_sample((1,5))

array([[0.25647424, 0.15242984, 0.71842665, 0.65719281, 0.5612166 ]])

   16) #numpy.random.uniform 
   This function is used to describe probability where every event has equal chances of occuring.

In [119]:
item= np.random.uniform(size=(1,5))
print(item)

[[0.58849856 0.3853261  0.83905263 0.80366586 0.17836217]]


17) #numpy.random.logistics This function is used to describe growth.

In [121]:
item= np.random.logistic(loc=1, scale=5, size=(1,5))
print(item)

[[ 5.89489834  3.72143057 14.06059843  3.02018291 -1.14636946]]


18) #numpy.diff This function is used to subtract two successive elements.

In [123]:
item= np.array([5,10,20,30,45,70])
newitem=np.diff(item)
print(newitem)

[ 5 10 10 15 25]


19) #numpy.log This function is used to perform log at the base.

In [128]:
item= np.arange(1,19) #base of 2
print(np.log2(item))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925   3.32192809 3.45943162 3.5849625
 3.70043972 3.80735492 3.9068906  4.         4.08746284 4.169925  ]


In [137]:
item= np.arange(1,19) #base of 10
print(np.log10(item))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.         1.04139269 1.07918125
 1.11394335 1.14612804 1.17609126 1.20411998 1.23044892 1.25527251]


20) #numpy.chisquare This function is used to verify the hypothesis using df(degree of freedom) and size.

In [136]:
from numpy import random
item=random.chisquare(df=5, size=(5,10))
print(item)

[[ 1.04175264  5.92274416  4.57494819  5.08267659  4.8867347   1.7874005
   6.87905225  3.2275397  15.33711855  6.39517586]
 [ 3.17234101  5.27356901  2.39043856  5.03459897  5.56019201  3.03130381
   9.56368275  4.36321054  6.75965874  0.60818762]
 [ 5.30913831  3.21632119  5.43663563  8.3299632   0.56794831  4.05771494
   5.92622203  6.56506011  2.06033628  2.99071812]
 [ 6.3403263   3.49080558  5.85284391  1.60919764  2.23486076  5.4843614
   4.36187942  2.4125982   4.20013628  2.0490207 ]
 [ 6.88445039  2.51602703  4.84935919  5.1895362   9.07863946  3.41582775
   6.8374018   1.46235357  3.10651983  1.80005649]]
