Write a NumPy program to get help on the add function.


In [1]:
import numpy as np


In [49]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

Write a NumPy program to create an array with values ranging from 12 to 38.


In [4]:
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [8]:
x = np.arange(2,11)
y = x.reshape(3,3)
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [24]:
x = np.ones((5,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
 x[1:-1,1:-1]= 0 
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Write a NumPy program to append values to the end of an array

In [39]:
arr = np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [44]:
arr = np.append(arr,[25])
print(arr)

[ 2  3  4  5  6  7  8  9 25]


Write a NumPy program to generate five random numbers from the normal
distribution.


In [47]:
normal_dist = np.random.randn(5)
print(normal_dist)

[ 0.26415673 -0.10569424  0.44783206 -0.88839365  0.65866467]


Write a NumPy program to get the n largest values of an array

In [48]:
normal_dist.max()

0.6586646679206324