In [1]:
import numpy as np
import pandas as pd

# Write down 20 in built methods on pandas and 20 on numpy with examples each.

# 20 in built methods on numpy

# 1) Amin
Return the minimum of an array or minimum along an axis

In [9]:
np.amin
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [10]:
np.amin(a)

0

# 2) Amax
Return the maximum of an array or maximum along an axis

In [6]:
A = np.arange(4).reshape((2,2))
A


array([[0, 1],
       [2, 3]])

In [7]:
np.amax(A)

3

# 3) Append
Append values to the end of an array

In [15]:
x = [5,10,15,20]
print(x)

[5, 10, 15, 20]


In [16]:
x= np.append(x,[25,30,35,40,45,50])
print(x)

[ 5 10 15 20 25 30 35 40 45 50]


# 4) Array_split
Split an array into multiple sub-arrays

In [19]:
y = np.arange(8.0)
np.array_split(y, 3)


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

# 5)Array_equal
True if two arrays have the same shape and elements, False otherwise.


In [20]:
np.array_equal([1, 2], [1, 2])

True

In [21]:
np.array_equal(np.array([1, 2]), np.array([1, 2]))

True

In [22]:
np.array_equal([1, 2], [1, 2, 3])

False

In [23]:
 np.array_equal([1, 2], [1, 4])

False

# 6) Average
Compute the weighted average along the specified axis


In [24]:
data = np.arange(1, 5)
data

array([1, 2, 3, 4])

In [25]:
np.average(data)

2.5

# 7) Concatenate
Join a sequence of arrays along an existing axis

In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [31]:
 np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# 8) Cumsum
Return the cumulative sum of the elements along a given axis

In [32]:
c = np.array([[1,2,3], [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.cumsum(c)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

# 9) Cumprod
Return the cumulative product of elements along a given axis

In [34]:
t= np.array([1,2,3])
np.cumprod(t)
# intermediate results 1, 1*2
...               # total product 1*2*3 = 6

array([1, 2, 6], dtype=int32)

In [35]:
u = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(u)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

# 10) Divide
Returns a true division of the inputs, element-wise

In [36]:
d = np.arange(5)
np.true_divide(d, 4)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 11) Delete
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
`arr[obj]`

In [37]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
 np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# 12) Diff
Calculate the n-th discrete difference along the given axis

In [39]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

In [40]:
np.diff(x, n=2)

array([  1,   1, -10])

In [41]:
 x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])
np.diff(x)

array([[2, 3, 4],
       [5, 1, 2]])

# 13) Dsplit
Split array into multiple sub-arrays along the 3rd axis (depth)

In [42]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [43]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

# 14) Greater_equal
Return the truth value of (x1 >= x2) element-wise

In [2]:
np.greater_equal([4, 2, 1], [2, 2, 2])

array([ True,  True, False])

In [3]:
 a = np.array([4, 2, 1])
 b = np.array([2, 2, 2])
 a >= b


array([ True,  True, False])

# 15) Greater
Return the truth value of (x1 > x2) element-wise.


In [4]:
np.greater([4,2],[2,2])

array([ True, False])

In [6]:
a = np.array([4, 2])
b = np.array([2, 2])
a > b

array([ True, False])

# 16) Less_equal
Return the truth value of (x1 <= x2) element-wise

In [ ]:
np.less_equal

In [9]:
np.less_equal([4, 2, 1], [2, 2, 2])

array([False,  True,  True])

In [10]:
a = np.array([4, 2, 1])
b = np.array([2, 2, 2])
a <= b

array([False,  True,  True])

# 17) Less
Return the truth value of (x1 < x2) element-wise

In [7]:
np.less([1, 2], [2, 2])

array([ True, False])

In [8]:
a = np.array([1, 2])
b = np.array([2, 2])
a < b

array([ True, False])

# 18) Equal
Return (x1 == x2) element-wise.

In [ ]:
np.equal

In [14]:
np.equal([0, 1, 3], np.arange(3))

array([ True,  True, False])

In [16]:
np.equal(1, np.ones(1))

array([ True])

In [15]:
a = np.array([2, 4, 6])
b = np.array([2, 4, 2])
a == b

array([ True,  True, False])

# 19) Not_equal
Return (x1 != x2) element-wise

In [11]:
np.not_equal([1.,2.], [1., 3.])

array([False,  True])

In [12]:
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

In [13]:
a = np.array([1., 2.])
b = np.array([1., 3.])
a != b

array([False,  True])

# 20) Reshape
Gives a new shape to an array without changing its data

In [ ]:
np.reshape

In [22]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

# 20 in built methods on pandas

# 1) Date_range
Return a fixed frequency DatetimeIndex

In [23]:
pd.date_range(start='1/1/2018', end='1/08/2018')

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

# 2) Concat
Concatenate pandas objects along a particular axis with optional set logic
along the other axes

In [92]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2])

0    a
1    b
0    c
1    d
dtype: object

# 3) Eval
Evaluate a Python expression as a string using various backends

In [27]:
df = pd.DataFrame({"animal": ["dog", "pig"], "age": [10, 20]})
df

animal  age
0    dog   10
1    pig   20

In [28]:
#We can add a new column using ``pd.eval``:
pd.eval("double_age = df.age * 2", target=df)

animal  age  double_age
0    dog   10          20
1    pig   20          40

# 4) Factorize
Encode the object as an enumerated type or categorical variable

In [29]:
uniques = pd.factorize(['b', 'b', 'a', 'c', 'b'])
uniques

(array([0, 0, 1, 2, 0], dtype=int64), array(['b', 'a', 'c'], dtype=object))

# 5)Interval_range
Return a fixed frequency IntervalIndex

In [30]:
pd.interval_range(start=0, end=5)

IntervalIndex([(0, 1], (1, 2], (2, 3], (3, 4], (4, 5]], dtype='interval[int64, right]')

# 6)Json_normalize
Normalize semi-structured JSON data into a flat table

In [32]:
data = [ {"id": 1, "name": {"first": "Coleen", "last": "Volk"}},
        {"name": {"given": "Mark", "family": "Regner"}},
        {"id": 2, "name": "Faye Raker"}, ]
data

[{'id': 1, 'name': {'first': 'Coleen', 'last': 'Volk'}},
 {'name': {'given': 'Mark', 'family': 'Regner'}},
 {'id': 2, 'name': 'Faye Raker'}]

In [33]:
pd.json_normalize(data)

id name.first name.last name.given name.family        name
0  1.0     Coleen      Volk        NaN         NaN         NaN
1  NaN        NaN       NaN       Mark      Regner         NaN
2  2.0        NaN       NaN        NaN         NaN  Faye Raker

# 7)lreshape
Reshape wide-format data to long. Generalized inverse of DataFrame.pivot.
Accepts a dictionary, ``groups``, in which each key is a new column name
and each value is a list of old column names that will be "melted" under
the new column name as part of the reshape.

In [48]:
data = pd.DataFrame({'hr1': [514, 573], 'hr2': [545, 526],
                      'team': ['Red Sox', 'Yankees'],
                      'year1': [2007, 2007], 'year2': [2008, 2008]})
data

hr1  hr2     team  year1  year2
0  514  545  Red Sox   2007   2008
1  573  526  Yankees   2007   2008

In [49]:
pd.lreshape(data, {'year': ['year1', 'year2'], 'hr': ['hr1', 'hr2']})

team  year   hr
0  Red Sox  2007  514
1  Yankees  2007  573
2  Red Sox  2008  545
3  Yankees  2008  526

# 8)Merge
Merge DataFrame or named Series objects with a database-style join

In [50]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                     'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
df1

lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [51]:
df2

rkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

In [52]:
df1.merge(df2, left_on='lkey', right_on='rkey')

lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

# 9)To_datetime
Convert argument to datetime.
This function converts a scalar, array-like, :class:`Series` or
:class:`DataFrame`/dict-like to a pandas datetime object.


In [54]:
df = pd.DataFrame({'year': [2015, 2016],
                   'month': [2, 3],
                   'day': [4, 5]})
pd.to_datetime(df)


0   2015-02-04
1   2016-03-05
dtype: datetime64[ns]

# 10) Append
Append rows of `other` to the end of caller, returning a new object

In [ ]:
df.append

In [56]:
df = pd.DataFrame([[1, 2], [3, 4]], columns=list('AB'), index=['x', 'y'])
df

A  B
x  1  2
y  3  4

In [57]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('AB'), index=['x', 'y'])
df2

A  B
x  5  6
y  7  8

In [61]:
df.append(df2)

C:\Users\USER\AppData\Local\Temp\ipykernel_408\2094904254.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df2)


A  B
x  1  2
y  3  4
x  5  6
y  7  8

# 11) Dropna
Remove missing values

In [62]:
df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
                   "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                            pd.NaT]})
df

name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [63]:
#Drop the rows where at least one element is missing.
df.dropna()

name        toy       born
1  Batman  Batmobile 1940-04-25

# 12) Drop
Drop specified labels from rows or columns

In [64]:
df = pd.DataFrame(np.arange(12).reshape(3, 4),
                   columns=['A', 'B', 'C', 'D'])
df

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [69]:
#Drop columns
df.drop(['B', 'C'], axis=1)

A   D
0  0   3
1  4   7
2  8  11

In [70]:
df.drop(columns=['B', 'C'])

A   D
0  0   3
1  4   7
2  8  11

In [71]:
#Drop a row by index
df.drop([0, 1])

A  B   C   D
2  8  9  10  11

# 13) Fillna
Fill NA/NaN values using the specified method

In [73]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                   [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, np.nan],
                   [np.nan, 3, np.nan, 4]],
                  columns=list("ABCD"))
df

A    B   C    D
0  NaN  2.0 NaN  0.0
1  3.0  4.0 NaN  1.0
2  NaN  NaN NaN  NaN
3  NaN  3.0 NaN  4.0

In [74]:
#Replace all NaN elements with 0s.
df.fillna(0)

A    B    C    D
0  0.0  2.0  0.0  0.0
1  3.0  4.0  0.0  1.0
2  0.0  0.0  0.0  0.0
3  0.0  3.0  0.0  4.0

# 14) Filter
Subset the dataframe rows or columns according to the specified index labels

In [75]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['one', 'two', 'three'])
df

one  two  three
mouse     1    2      3
rabbit    4    5      6

In [76]:
# select columns by name
df.filter(items=['one', 'three'])

one  three
mouse     1      3
rabbit    4      6

# 15) Describe
Generate descriptive statistics

In [77]:
s = pd.Series([1, 2, 3])
s.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

# 16) Groupby
Group DataFrame using a mapper or by a Series of columns

In [78]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'Max Speed': [380., 370., 24., 26.]})
df

Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [90]:
df.groupby(['Animal']).mean()

Max Speed
Animal           
Falcon      375.0
Parrot       25.0

# 17) Head
Return the first `n` rows.
This function returns the first `n` rows for the object based
on position. It is useful for quickly testing if your object
has the right type of data in it.
For negative values of `n`, this function returns all rows except
the last `n` rows, equivalent to ``df[:-n]``.

In [ ]:
df.head

In [93]:
df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
                              'monkey', 'parrot', 'shark', 'whale', 'zebra']})
df

animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

In [95]:
#viewing the first five lines
df.head()

animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey

In [96]:
#viewing the first two lines
df.head(2)

animal
0  alligator
1        bee

# 18) Tail
Return the last `n` rows.
This function returns last `n` rows from the object based on
position. It is useful for quickly verifying data, for example,
after sorting or appending rows.
For negative values of `n`, this function returns all rows except
the first `n` rows, equivalent to ``df[n:]``.

In [ ]:
df.tail

In [97]:
df = pd.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
df

animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra

In [98]:
#Viewing the last 5 lines
df.tail()

animal
4  monkey
5  parrot
6   shark
7   whale
8   zebra

In [99]:
#Viewing the last 2 lines
df.tail(2)

animal
7  whale
8  zebra

# 19) Update
Modify in place using non-NA values from another DataFrame

In [100]:
df = pd.DataFrame({'A': [1, 2, 3],
                   'B': [400, 500, 600]})
df

A    B
0  1  400
1  2  500
2  3  600

In [106]:
new_df = pd.DataFrame({'B': [4, 5, 6],
                       'C': [7, 8, 9]})
df.update(new_df)  #only values at matching index are updated
df

A  B
0  1  4
1  2  5
2  3  6

# 20) Transpose
Transpose index and columns.
Reflect the DataFrame over its main diagonal by writing rows as columns
and vice-versa.

In [107]:
d1 = {'col1': [1, 2], 'col2': [3, 4]}
df1 = pd.DataFrame(data=d1)
df1

col1  col2
0     1     3
1     2     4

In [108]:
df1.transpose()

0  1
col1  1  2
col2  3  4