In [1]:
#20 Numpy and Pandas in-built functions with examples

In [1]:
import pandas as pd
import numpy as np

In [10]:
# pd.DataFrame is used to tabulate data
people= {'Name':['Ami','Ben','Nas'],'Age': ['16', '14', '22'], 'Gender': ['female','male','male']}
print(type(people))
df= pd.DataFrame(data=people)
df

<class 'dict'>


Name Age  Gender
0  Ami  16  female
1  Ben  14    male
2  Nas  22    male

In [13]:
#.iloc is used for integer-location indexing
df.iloc[0].Name

'Ami'

In [15]:
#.loc is used for label indexing
df.loc[0]

Name         Ami
Age           16
Gender    female
Name: 0, dtype: object

In [16]:
#describe gives description statistics of all columns in a dataframe
df.describe()

Name Age Gender
count     3   3      3
unique    3   3      2
top     Ami  16   male
freq      1   1      2

In [20]:
#count function
df.count()

Name      3
Age       3
Gender    3
dtype: int64

In [9]:
#numpy functions
#1. np.zeros
np.zeros( (3,4) )


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
#np.empty to create an uninitialized array of random data.
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#np.arange to create a sequenced array
np.arange( 10, 30, 5 ) 

array([10, 15, 20, 25])

In [12]:
#np.linspace with an argument describing the number of elements 
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
#np.ones 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#reshape redefines the dimention of array
a = np.arange(15).reshape(3, 5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])