##  Research and write down 20 in built method on pandas and 20 on numpy with examples each.

# 20 BUILT-IN METHODS OF PANDAS

### To do this, I will be importing a dataset to work on titled: "diabetes.csv"

In [12]:
# I will import pandas as pd


import pandas as pd

In [13]:
# I will get the dataset using the .read_csv function


data = pd.read_csv("C://diabetes.csv")

In [14]:
# Function 1: The .head() function is used to get the first five rows of the dataframe


data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [15]:
# Function 2: The .tail() function is used to get the last five rows of the dataframe


data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [16]:
# Function 3: The .info() function is used to get the information of the dataframe


data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [17]:
# Function 4: The .dtypes function shows us the datatype of each column


data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [10]:
# Function 5: The .shape function is used to show the number of dimensions in a dataframe. That is, how many rows and columns are present in the dataset


data.shape

(768, 9)

In [18]:
# Function 6: The .size function is used to get the rows, multiplied by the column of the dataframe


data.size

6912

In [19]:
# Function 7: The .describe() function is used to get a quick statistical summary of every numerical column


data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [20]:
#The transpose operator is used to switch from columns to rows, and vice-versa

data.describe(include='all').T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [21]:
# Function 8: The sample method helps one to select a random sample from the distribution, where n is the number of samples desired to be displayed.


data.sample(n=6)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
334            1       95             60             18       58  23.9   
536            0      105             90              0        0  29.6   
235            4      171             72              0        0  43.6   
212            7      179             95             31        0  34.2   
139            5      105             72             29      325  36.9   
388            5      144             82             26      285  32.0   

     DiabetesPedigreeFunction  Age  Outcome  
334                     0.260   22        0  
536                     0.197   46        0  
235                     0.479   26        1  
212                     0.164   60        0  
139                     0.159   28        0  
388                     0.452   58        1

In [22]:
# Function 9: The isnull() function helps to identify the missing values in a dataset, a crucial step in data analysis.


data.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [27]:
#Function 10: The isna() functions helps return missing values indicated by the True boolean value in the dataframe


data.isna().any()


Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [28]:
# Function 11: The isnull().sum() function calculates the number of missing values in each column


data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [29]:
# Function 12: The .nsmallest function prints out the observation with the smallest values based on the column called


data.nsmallest(4, 'Glucose')

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
75             1        0             48             20        0  24.7   
182            1        0             74             20       23  27.7   
342            1        0             68             35        0  32.0   
349            5        0             80             32        0  41.0   

     DiabetesPedigreeFunction  Age  Outcome  
75                      0.140   22        0  
182                     0.299   21        0  
342                     0.389   22        0  
349                     0.346   37        1

In [30]:
# Function 13: The .nlargest function prints out the observation with the largest values based on the column called, and number of rows selected


data.nlargest(7, 'BloodPressure')

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
106            1       96            122              0        0  22.4   
691           13      158            114              0        0  42.3   
43             9      171            110             24      240  45.4   
177            0      129            110             46      130  67.1   
549            4      189            110             31        0  28.5   
84             5      137            108              0        0  48.8   
362            5      103            108             37        0  39.2   

     DiabetesPedigreeFunction  Age  Outcome  
106                     0.207   27        0  
691                     0.257   44        1  
43                      0.721   54        1  
177                     0.319   26        1  
549                     0.680   37        0  
84                      0.227   37        1  
362                     0.305   65        0

In [31]:
# Function 14: The loc and iloc functions are used to selct rows and columns by labels and positions respectively.

# To select the first 4 rows and 3 columns with loc;


data.loc[:3,['Pregnancies', 'Glucose', 'BloodPressure']]

Pregnancies  Glucose  BloodPressure
0            6      148             72
1            1       85             66
2            8      183             64
3            1       89             66

In [32]:
# As stated above, selecting the first 10 rows and first 5 columns with iloc;



data.iloc[:10,:5]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin
0            6      148             72             35        0
1            1       85             66             29        0
2            8      183             64              0        0
3            1       89             66             23       94
4            0      137             40             35      168
5            5      116             74              0        0
6            3       78             50             32       88
7           10      115              0              0        0
8            2      197             70             45      543
9            8      125             96              0        0

In [35]:
# Function 15: The groupby function is used to reveal relationships among variables


data.groupby(['Pregnancies', 'Glucose', 'BloodPressure']).mean()

SkinThickness  Insulin   BMI  \
Pregnancies Glucose BloodPressure                                 
0           57      60                       0.0      0.0  21.7   
            67      76                       0.0      0.0  45.3   
            73      0                        0.0      0.0  21.1   
            74      52                      10.0     36.0  27.8   
            78      88                      29.0     40.0  36.9   
...                                          ...      ...   ...   
13          158     114                      0.0      0.0  42.3   
14          100     78                      25.0    184.0  36.6   
            175     62                      30.0      0.0  33.6   
15          136     70                      32.0    110.0  37.1   
17          163     72                      41.0    114.0  40.9   

                                   DiabetesPedigreeFunction   Age  Outcome  
Pregnancies Glucose BloodPressure                                           
0           57      60                                0.735  67.0      0.0  
            67      76                                0.194  46.0      0.0  
            73      0                                 0.342  25.0      0.0  
            74      52                                0.269  22.0      0.0  
            78      88                                0.434  21.0      0.0  
...                                                     ...   ...      ...  
13          158     114                               0.257  44.0      1.0  
14          100     78                                0.412  46.0      1.0  
            175     62                                0.212  38.0      1.0  
15          136     70                                0.153  43.0      1.0  
17          163     72                                0.817  47.0      1.0  

[754 rows x 6 columns]

In [36]:
# Function 16: The .query() function is used to filter a dataframe based on a condition or tweak the dataframe to get certain values


data.query('30 < Age <70')[:10]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6   
1             1       85             66             29        0  26.6   
2             8      183             64              0        0  23.3   
4             0      137             40             35      168  43.1   
8             2      197             70             45      543  30.5   
9             8      125             96              0        0   0.0   
11           10      168             74              0        0  38.0   
12           10      139             80              0        0  27.1   
13            1      189             60             23      846  30.1   
14            5      166             72             19      175  25.8   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50        1  
1                      0.351   31        0  
2                      0.672   32        1  
4                      2.288   33        1  
8                      0.158   53        1  
9                      0.232   54        1  
11                     0.537   34        1  
12                     1.441   57        0  
13                     0.398   59        1  
14                     0.587   51        1

In [44]:
# Function 17: The insert function helps to add a new column in any position into the dataframe


#creating the new column
new = 6
new_column = 5

#inserting the new column at position 2

data.insert(2, 'new', new)
data.insert(3, 'new_column', new_column)




In [45]:
data.head()

Pregnancies  Glucose  new  new_column  BloodPressure  SkinThickness  \
0            6      148    6           5             72             35   
1            1       85    6           5             66             29   
2            8      183    6           5             64              0   
3            1       89    6           5             66             23   
4            0      137    6           5             40             35   

   Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome  
0        0  33.6                     0.627   50        1  
1        0  26.6                     0.351   31        0  
2        0  23.3                     0.672   32        1  
3       94  28.1                     0.167   21        0  
4      168  43.1                     2.288   33        1

In [46]:
# Function 18: The drop function is used to remove unwanted column from the dataframe


drop_column = ['new']
data.drop(drop_column,axis=1,inplace=True)

In [47]:
data

Pregnancies  Glucose  new_column  BloodPressure  SkinThickness  Insulin  \
0              6      148           5             72             35        0   
1              1       85           5             66             29        0   
2              8      183           5             64              0        0   
3              1       89           5             66             23       94   
4              0      137           5             40             35      168   
..           ...      ...         ...            ...            ...      ...   
763           10      101           5             76             48      180   
764            2      122           5             70             27        0   
765            5      121           5             72             23      112   
766            1      126           5             60              0        0   
767            1       93           5             70             31        0   

      BMI  DiabetesPedigreeFunction  Age  Outcome  
0    33.6                     0.627   50        1  
1    26.6                     0.351   31        0  
2    23.3                     0.672   32        1  
3    28.1                     0.167   21        0  
4    43.1                     2.288   33        1  
..    ...                       ...  ...      ...  
763  32.9                     0.171   63        0  
764  36.8                     0.340   27        0  
765  26.2                     0.245   30        0  
766  30.1                     0.349   47        1  
767  30.4                     0.315   23        0  

[768 rows x 10 columns]

In [49]:
# Function 19: The len function provides the length(number of rows) of the dataframe


len(data)

768

In [50]:
# Function 20: The .cumsum function helps to calculate the cumulative sum of selected collumns


data[['Pregnancies', 'Glucose']].cumsum()

Pregnancies  Glucose
0              6      148
1              7      233
2             15      416
3             16      505
4             16      642
..           ...      ...
763         2944    92385
764         2946    92507
765         2951    92628
766         2952    92754
767         2953    92847

[768 rows x 2 columns]

# 20 INBUILT METHODS OF NUMPY

In [51]:
# I will import the numpy library as np


import numpy as np

In [56]:
#Function 1: The np.array function is used to create an array of numbers


numbers = np.array([2, 3, 4, 5, ])

numbers

array([2, 3, 4, 5])

In [54]:
# Function2: The linspace function returns evenly spaced numbers over a specified interval


np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [57]:
#Function 3: Thenp.repeat function repeats the elements of an array


np.repeat(20,50)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [59]:
#Function 4: The random fumction is used to call random numbers

#For example, to roll a dice 10 times


np.random.randint(1,7,10)


array([6, 3, 1, 4, 2, 2, 1, 1, 4, 1])

In [60]:
# Function 5: .log returns an element-wise logarithm for an array


np.log(5)

1.6094379124341003

In [65]:
#Function 6: reshape() function rearranges the data of the nd array to a new shape


array = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17])

array.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [66]:
# Function 7: The sum() function sums upall the elements of aver a given axis


array.sum()

81

In [67]:
# Function 8: The transpose function reverses or permutes the axes of an ndarray


array.transpose()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [71]:
#Function 9: The np.zeros function craetes an array full of zeroes


np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
#Function 10: The np.ones function craetes an array full of ones


np.ones((3,4,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [73]:
# Function 11: The arange function is used to create a sequence of numbers in an array


np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [74]:
# Function 12: The universal functions


arr = ([1, 2, 3, 4, 5, 6, 7])

#To get the exponential factor
np.exp(arr)


#To get the the square root
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [75]:
# Function 13: The add function sums two arrays up

A = np.array([3, 6, 8])
B = np.array([1, 5, 9])

np.add(A,B)

array([ 4, 11, 17])

In [77]:
#Function 14: The trigonometric functions
from math import pi


a = ([2, 4, 6, 8, 10])
np.sin(a)


np.cos(a)

array([-0.41614684, -0.65364362,  0.96017029, -0.14550003, -0.83907153])

In [80]:
# Function 15: The np.around function rounds up to the desired precision


a = ([2, 4, 6, 8, 10])

np.around(a,decimals=1)

array([ 2,  4,  6,  8, 10])

In [82]:
# Function 16: The np.floor function rounds up to the desired precision


floored = ([2.3, 4.5, 6.7, 8.9, 10.1])

np.floor(floored)

array([ 2.,  4.,  6.,  8., 10.])

In [83]:
# Function 17: The np.ceil function returns the ceiling of an input value i.e. the ceil of the scalar x is the smallest integer i, such that i >= x


ceiled = ([0.3, 9.5, 4.7, 6.98, 18.1])

np.ceil(ceiled)

array([ 1., 10.,  5.,  7., 19.])

In [87]:
#Function 18: The amin() function prints the minimum value in the array


c = np.array([[3,7,5],[8,4,3],[2,4,9]]) 


np.min(c,1)

array([3, 3, 2])

In [89]:
# Function 19:The amax() function prints the maximum value in the array



a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
np.amax(c, axis=0)

array([8, 7, 9])

In [90]:
#Function 20: The copy function is used to copy an array without making changes to it.



arr1 = np.array([1, 2, 3, 4, 5]) 
y = arr1.copy() 
arr1[0] = 36 
print(arr1) 
print(y)

[36  2  3  4  5]
[1 2 3 4 5]
