## NumPy & Pandas Built-In Methods with Examples

In [1]:
#import required NumPy and Pandas
import numpy as np
import pandas as pd

In [ ]:
#datasets used in the exercise
Used dataset from Kaggle

### NumPy

1. np.array()
Creates a one dimensional array

In [27]:
l = [ 6, 5, 8, 3,7]
a = np.array(l)
print(a)
type(a)

[6 5 8 3 7]


numpy.ndarray

2. np.sort()
Sorts array with values in ascending order

In [29]:
print(np.sort(a)) # uses array a in number 1
type(a)

[3 5 6 7 8]


numpy.ndarray

3. np.linspace(start, stop, step)
Creates a new 1D numpy array with evenly spread elements
within the given interval

In [37]:
print(np.linspace( 0 , 10 , 50 ))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


4. np.average()
Averages over all the values in the numpy array

In [38]:
print(np.average(a))

5.8


5. np.argsort()
Returns the indices of a NumPy array so that the indexed values would be sorted.

In [39]:
print(np.argsort(a))

[3 1 0 4 2]


### Pandas

1. Series()
Creates a Series by passing a list of values letting pandas create a default integer index

In [30]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)
type(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


pandas.core.series.Series

2. read_csv()
Import CSV; allows a user to create a Pandas Dataframe from a local CSV.

In [12]:
df = pd.read_csv('B:\WTF\Week 9\healthy_lifestyle_city_2021.csv')

3. head()
Displays the first 5 rows in a dataframe

In [13]:
df.head()

City  Rank Sunshine hours(City) Cost of a bottle of water(City)  \
0   Amsterdam     1                 1858                           £1.92   
1      Sydney     2                 2636                           £1.48   
2      Vienna     3                 1884                           £1.94   
3   Stockholm     4                 1821                           £1.72   
4  Copenhagen     5                 1630                           £2.19   

  Obesity levels(Country)  Life expectancy(years) (Country)  \
0                  20.40%                              81.2   
1                  29.00%                              82.1   
2                  20.10%                              81.0   
3                  20.60%                              81.8   
4                  19.70%                              79.8   

  Pollution(Index score) (City) Annual avg. hours worked  \
0                         30.93                     1434   
1                         26.86                     1712   
2                         17.33                     1501   
3                         19.63                     1452   
4                         21.24                     1380   

   Happiness levels(Country)  Outdoor activities(City)  \
0                       7.44                       422   
1                       7.22                       406   
2                       7.29                       132   
3                       7.35                       129   
4                       7.64                       154   

   Number of take out places(City) Cost of a monthly gym membership(City)  
0                             1048                                 £34.90  
1                             1103                                 £41.66  
2                             1008                                 £25.74  
3                              598                                 £37.31  
4                              523                                 £32.53

4. sort_values()
Pass a column name and specify ascending = True or False to sort the dataframe by that column.

In [22]:
df2 = df.sort_values('Sunshine hours(City)',ascending=True)
print(df2.head())

        City  Rank Sunshine hours(City) Cost of a bottle of water(City)  \
19    Geneva    20                    -                           £2.62   
23    Taipei    24                 1405                           £0.57   
27    Dublin    28                 1453                           £1.40   
32  Brussels    33                 1546                           £2.11   
36    Zurich    37                 1566                           £3.20   

   Obesity levels(Country)  Life expectancy(years) (Country)  \
19                  19.50%                              82.6   
23                   6.20%                              75.4   
27                  25.30%                              80.5   
32                  22.10%                              80.4   
36                  19.50%                              82.6   

   Pollution(Index score) (City) Annual avg. hours worked  \
19                         27.25                     1557   
23                         49.32          

5. to_csv()
Export the CSV; use this method to save your dataframe to local storage.

In [34]:
df.to_csv('B:\WTF\Week 9\healthy_lifestyle_city_2021_sorted.csv')